//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace Power.SPMEMS.Services.Models
{
	/// <summary>
	/// 实体类DCPRJJDMST。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("DCPRJJDMST")]
	[Serializable]
	[DataContract]
	public partial class DCPRJJDMST : Entity
	{
		#region Model
		private int _PRJJD_NO;
		private string _PRJJD_ID;
		private string _PRJJD_NAM;
		private int? _ORG_NO;
		private string _PRJJD_SHT;
		private string _FSTUSR_ID;
		private DateTime? _FSTUSR_DTM;
		private string _LSTUSR_ID;
		private DateTime? _LSTUSR_DTM;
		private string _REP_ID;
		private string _PRJJD_STA;
		private int? _PRJJD_SEQ;
		private string _PRJJD_TYP;
		private int? _ZBFS;
		private int? _DZFS;

		/// <summary>
		/// 
		/// </summary>
		[Field("PRJJD_NO")]
		[DataMember]
		public int PRJJD_NO
		{
			get { return _PRJJD_NO; }
			set
			{
				this.OnPropertyValueChange("PRJJD_NO");
				this._PRJJD_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PRJJD_ID")]
		[DataMember]
		public string PRJJD_ID
		{
			get { return _PRJJD_ID; }
			set
			{
				this.OnPropertyValueChange("PRJJD_ID");
				this._PRJJD_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PRJJD_NAM")]
		[DataMember]
		public string PRJJD_NAM
		{
			get { return _PRJJD_NAM; }
			set
			{
				this.OnPropertyValueChange("PRJJD_NAM");
				this._PRJJD_NAM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ORG_NO")]
		[DataMember]
		public int? ORG_NO
		{
			get { return _ORG_NO; }
			set
			{
				this.OnPropertyValueChange("ORG_NO");
				this._ORG_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PRJJD_SHT")]
		[DataMember]
		public string PRJJD_SHT
		{
			get { return _PRJJD_SHT; }
			set
			{
				this.OnPropertyValueChange("PRJJD_SHT");
				this._PRJJD_SHT = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FSTUSR_ID")]
		[DataMember]
		public string FSTUSR_ID
		{
			get { return _FSTUSR_ID; }
			set
			{
				this.OnPropertyValueChange("FSTUSR_ID");
				this._FSTUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FSTUSR_DTM")]
		[DataMember]
		public DateTime? FSTUSR_DTM
		{
			get { return _FSTUSR_DTM; }
			set
			{
				this.OnPropertyValueChange("FSTUSR_DTM");
				this._FSTUSR_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LSTUSR_ID")]
		[DataMember]
		public string LSTUSR_ID
		{
			get { return _LSTUSR_ID; }
			set
			{
				this.OnPropertyValueChange("LSTUSR_ID");
				this._LSTUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LSTUSR_DTM")]
		[DataMember]
		public DateTime? LSTUSR_DTM
		{
			get { return _LSTUSR_DTM; }
			set
			{
				this.OnPropertyValueChange("LSTUSR_DTM");
				this._LSTUSR_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("REP_ID")]
		[DataMember]
		public string REP_ID
		{
			get { return _REP_ID; }
			set
			{
				this.OnPropertyValueChange("REP_ID");
				this._REP_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PRJJD_STA")]
		[DataMember]
		public string PRJJD_STA
		{
			get { return _PRJJD_STA; }
			set
			{
				this.OnPropertyValueChange("PRJJD_STA");
				this._PRJJD_STA = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PRJJD_SEQ")]
		[DataMember]
		public int? PRJJD_SEQ
		{
			get { return _PRJJD_SEQ; }
			set
			{
				this.OnPropertyValueChange("PRJJD_SEQ");
				this._PRJJD_SEQ = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PRJJD_TYP")]
		[DataMember]
		public string PRJJD_TYP
		{
			get { return _PRJJD_TYP; }
			set
			{
				this.OnPropertyValueChange("PRJJD_TYP");
				this._PRJJD_TYP = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ZBFS")]
		[DataMember]
		public int? ZBFS
		{
			get { return _ZBFS; }
			set
			{
				this.OnPropertyValueChange("ZBFS");
				this._ZBFS = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DZFS")]
		[DataMember]
		public int? DZFS
		{
			get { return _DZFS; }
			set
			{
				this.OnPropertyValueChange("DZFS");
				this._DZFS = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.PRJJD_NO,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.PRJJD_NO,
				_.PRJJD_ID,
				_.PRJJD_NAM,
				_.ORG_NO,
				_.PRJJD_SHT,
				_.FSTUSR_ID,
				_.FSTUSR_DTM,
				_.LSTUSR_ID,
				_.LSTUSR_DTM,
				_.REP_ID,
				_.PRJJD_STA,
				_.PRJJD_SEQ,
				_.PRJJD_TYP,
				_.ZBFS,
				_.DZFS,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._PRJJD_NO,
				this._PRJJD_ID,
				this._PRJJD_NAM,
				this._ORG_NO,
				this._PRJJD_SHT,
				this._FSTUSR_ID,
				this._FSTUSR_DTM,
				this._LSTUSR_ID,
				this._LSTUSR_DTM,
				this._REP_ID,
				this._PRJJD_STA,
				this._PRJJD_SEQ,
				this._PRJJD_TYP,
				this._ZBFS,
				this._DZFS,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "DCPRJJDMST");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PRJJD_NO = new Field("PRJJD_NO", "DCPRJJDMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PRJJD_ID = new Field("PRJJD_ID", "DCPRJJDMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PRJJD_NAM = new Field("PRJJD_NAM", "DCPRJJDMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ORG_NO = new Field("ORG_NO", "DCPRJJDMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PRJJD_SHT = new Field("PRJJD_SHT", "DCPRJJDMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FSTUSR_ID = new Field("FSTUSR_ID", "DCPRJJDMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FSTUSR_DTM = new Field("FSTUSR_DTM", "DCPRJJDMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LSTUSR_ID = new Field("LSTUSR_ID", "DCPRJJDMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LSTUSR_DTM = new Field("LSTUSR_DTM", "DCPRJJDMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field REP_ID = new Field("REP_ID", "DCPRJJDMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PRJJD_STA = new Field("PRJJD_STA", "DCPRJJDMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PRJJD_SEQ = new Field("PRJJD_SEQ", "DCPRJJDMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PRJJD_TYP = new Field("PRJJD_TYP", "DCPRJJDMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ZBFS = new Field("ZBFS", "DCPRJJDMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DZFS = new Field("DZFS", "DCPRJJDMST", "");
		}
		#endregion
	}
}