//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace Power.SPMEMS.Services.Models
{
	/// <summary>
	/// 实体类DCWTRECMST。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("DCWTRECMST")]
	[Serializable]
	[DataContract]
	public partial class DCWTRECMST : Entity
	{
		#region Model
		private int _REC_NO;
		private int? _ORG_NO;
		private string _REC_STA;
		private string _YEAR;
		private int? _CURWEEK;
		private int? _SUMWEEK;
		private string _REC_USR;
		private int? _REC_CST;
		private DateTime? _BEG_DTM;
		private DateTime? _END_DTM;
		private int? _SUMFDWT;
		private int? _SUMACTWT;
		private string _FSTUSR_ID;
		private DateTime? _FSTUSR_DTM;
		private string _LSTUSR_ID;
		private DateTime? _LSTUSR_DTM;
		private string _REC_ID;
		private DateTime? _WK1;
		private DateTime? _WK6;
		private int? _TUEW;
		private int? _WEDW;
		private int? _THUW;
		private int? _MONW;
		private int? _FIRW;
		private int? _SATW;
		private int? _SUNW;
		private int? _SUMW1;
		private int? _SUMW2;
		private int? _SUMW3;
		private int? _SUMW4;
		private int? _SUMW5;
		private int? _SUMW6;
		private int? _SUMW7;
		private int? _SUMJ1;
		private int? _SUMJ2;
		private int? _SUMJ3;
		private int? _SUMJ4;
		private int? _SUMJ5;
		private int? _SUMJ6;
		private int? _SUMJ7;
		private string _CURWEEK_DSC;

		/// <summary>
		/// 
		/// </summary>
		[Field("REC_NO")]
		[DataMember]
		public int REC_NO
		{
			get { return _REC_NO; }
			set
			{
				this.OnPropertyValueChange("REC_NO");
				this._REC_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ORG_NO")]
		[DataMember]
		public int? ORG_NO
		{
			get { return _ORG_NO; }
			set
			{
				this.OnPropertyValueChange("ORG_NO");
				this._ORG_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("REC_STA")]
		[DataMember]
		public string REC_STA
		{
			get { return _REC_STA; }
			set
			{
				this.OnPropertyValueChange("REC_STA");
				this._REC_STA = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("YEAR")]
		[DataMember]
		public string YEAR
		{
			get { return _YEAR; }
			set
			{
				this.OnPropertyValueChange("YEAR");
				this._YEAR = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CURWEEK")]
		[DataMember]
		public int? CURWEEK
		{
			get { return _CURWEEK; }
			set
			{
				this.OnPropertyValueChange("CURWEEK");
				this._CURWEEK = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SUMWEEK")]
		[DataMember]
		public int? SUMWEEK
		{
			get { return _SUMWEEK; }
			set
			{
				this.OnPropertyValueChange("SUMWEEK");
				this._SUMWEEK = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("REC_USR")]
		[DataMember]
		public string REC_USR
		{
			get { return _REC_USR; }
			set
			{
				this.OnPropertyValueChange("REC_USR");
				this._REC_USR = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("REC_CST")]
		[DataMember]
		public int? REC_CST
		{
			get { return _REC_CST; }
			set
			{
				this.OnPropertyValueChange("REC_CST");
				this._REC_CST = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("BEG_DTM")]
		[DataMember]
		public DateTime? BEG_DTM
		{
			get { return _BEG_DTM; }
			set
			{
				this.OnPropertyValueChange("BEG_DTM");
				this._BEG_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("END_DTM")]
		[DataMember]
		public DateTime? END_DTM
		{
			get { return _END_DTM; }
			set
			{
				this.OnPropertyValueChange("END_DTM");
				this._END_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SUMFDWT")]
		[DataMember]
		public int? SUMFDWT
		{
			get { return _SUMFDWT; }
			set
			{
				this.OnPropertyValueChange("SUMFDWT");
				this._SUMFDWT = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SUMACTWT")]
		[DataMember]
		public int? SUMACTWT
		{
			get { return _SUMACTWT; }
			set
			{
				this.OnPropertyValueChange("SUMACTWT");
				this._SUMACTWT = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FSTUSR_ID")]
		[DataMember]
		public string FSTUSR_ID
		{
			get { return _FSTUSR_ID; }
			set
			{
				this.OnPropertyValueChange("FSTUSR_ID");
				this._FSTUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FSTUSR_DTM")]
		[DataMember]
		public DateTime? FSTUSR_DTM
		{
			get { return _FSTUSR_DTM; }
			set
			{
				this.OnPropertyValueChange("FSTUSR_DTM");
				this._FSTUSR_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LSTUSR_ID")]
		[DataMember]
		public string LSTUSR_ID
		{
			get { return _LSTUSR_ID; }
			set
			{
				this.OnPropertyValueChange("LSTUSR_ID");
				this._LSTUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LSTUSR_DTM")]
		[DataMember]
		public DateTime? LSTUSR_DTM
		{
			get { return _LSTUSR_DTM; }
			set
			{
				this.OnPropertyValueChange("LSTUSR_DTM");
				this._LSTUSR_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("REC_ID")]
		[DataMember]
		public string REC_ID
		{
			get { return _REC_ID; }
			set
			{
				this.OnPropertyValueChange("REC_ID");
				this._REC_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("WK1")]
		[DataMember]
		public DateTime? WK1
		{
			get { return _WK1; }
			set
			{
				this.OnPropertyValueChange("WK1");
				this._WK1 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("WK6")]
		[DataMember]
		public DateTime? WK6
		{
			get { return _WK6; }
			set
			{
				this.OnPropertyValueChange("WK6");
				this._WK6 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TUEW")]
		[DataMember]
		public int? TUEW
		{
			get { return _TUEW; }
			set
			{
				this.OnPropertyValueChange("TUEW");
				this._TUEW = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("WEDW")]
		[DataMember]
		public int? WEDW
		{
			get { return _WEDW; }
			set
			{
				this.OnPropertyValueChange("WEDW");
				this._WEDW = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("THUW")]
		[DataMember]
		public int? THUW
		{
			get { return _THUW; }
			set
			{
				this.OnPropertyValueChange("THUW");
				this._THUW = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MONW")]
		[DataMember]
		public int? MONW
		{
			get { return _MONW; }
			set
			{
				this.OnPropertyValueChange("MONW");
				this._MONW = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FIRW")]
		[DataMember]
		public int? FIRW
		{
			get { return _FIRW; }
			set
			{
				this.OnPropertyValueChange("FIRW");
				this._FIRW = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SATW")]
		[DataMember]
		public int? SATW
		{
			get { return _SATW; }
			set
			{
				this.OnPropertyValueChange("SATW");
				this._SATW = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SUNW")]
		[DataMember]
		public int? SUNW
		{
			get { return _SUNW; }
			set
			{
				this.OnPropertyValueChange("SUNW");
				this._SUNW = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SUMW1")]
		[DataMember]
		public int? SUMW1
		{
			get { return _SUMW1; }
			set
			{
				this.OnPropertyValueChange("SUMW1");
				this._SUMW1 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SUMW2")]
		[DataMember]
		public int? SUMW2
		{
			get { return _SUMW2; }
			set
			{
				this.OnPropertyValueChange("SUMW2");
				this._SUMW2 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SUMW3")]
		[DataMember]
		public int? SUMW3
		{
			get { return _SUMW3; }
			set
			{
				this.OnPropertyValueChange("SUMW3");
				this._SUMW3 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SUMW4")]
		[DataMember]
		public int? SUMW4
		{
			get { return _SUMW4; }
			set
			{
				this.OnPropertyValueChange("SUMW4");
				this._SUMW4 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SUMW5")]
		[DataMember]
		public int? SUMW5
		{
			get { return _SUMW5; }
			set
			{
				this.OnPropertyValueChange("SUMW5");
				this._SUMW5 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SUMW6")]
		[DataMember]
		public int? SUMW6
		{
			get { return _SUMW6; }
			set
			{
				this.OnPropertyValueChange("SUMW6");
				this._SUMW6 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SUMW7")]
		[DataMember]
		public int? SUMW7
		{
			get { return _SUMW7; }
			set
			{
				this.OnPropertyValueChange("SUMW7");
				this._SUMW7 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SUMJ1")]
		[DataMember]
		public int? SUMJ1
		{
			get { return _SUMJ1; }
			set
			{
				this.OnPropertyValueChange("SUMJ1");
				this._SUMJ1 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SUMJ2")]
		[DataMember]
		public int? SUMJ2
		{
			get { return _SUMJ2; }
			set
			{
				this.OnPropertyValueChange("SUMJ2");
				this._SUMJ2 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SUMJ3")]
		[DataMember]
		public int? SUMJ3
		{
			get { return _SUMJ3; }
			set
			{
				this.OnPropertyValueChange("SUMJ3");
				this._SUMJ3 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SUMJ4")]
		[DataMember]
		public int? SUMJ4
		{
			get { return _SUMJ4; }
			set
			{
				this.OnPropertyValueChange("SUMJ4");
				this._SUMJ4 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SUMJ5")]
		[DataMember]
		public int? SUMJ5
		{
			get { return _SUMJ5; }
			set
			{
				this.OnPropertyValueChange("SUMJ5");
				this._SUMJ5 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SUMJ6")]
		[DataMember]
		public int? SUMJ6
		{
			get { return _SUMJ6; }
			set
			{
				this.OnPropertyValueChange("SUMJ6");
				this._SUMJ6 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SUMJ7")]
		[DataMember]
		public int? SUMJ7
		{
			get { return _SUMJ7; }
			set
			{
				this.OnPropertyValueChange("SUMJ7");
				this._SUMJ7 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CURWEEK_DSC")]
		[DataMember]
		public string CURWEEK_DSC
		{
			get { return _CURWEEK_DSC; }
			set
			{
				this.OnPropertyValueChange("CURWEEK_DSC");
				this._CURWEEK_DSC = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.REC_NO,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.REC_NO,
				_.ORG_NO,
				_.REC_STA,
				_.YEAR,
				_.CURWEEK,
				_.SUMWEEK,
				_.REC_USR,
				_.REC_CST,
				_.BEG_DTM,
				_.END_DTM,
				_.SUMFDWT,
				_.SUMACTWT,
				_.FSTUSR_ID,
				_.FSTUSR_DTM,
				_.LSTUSR_ID,
				_.LSTUSR_DTM,
				_.REC_ID,
				_.WK1,
				_.WK6,
				_.TUEW,
				_.WEDW,
				_.THUW,
				_.MONW,
				_.FIRW,
				_.SATW,
				_.SUNW,
				_.SUMW1,
				_.SUMW2,
				_.SUMW3,
				_.SUMW4,
				_.SUMW5,
				_.SUMW6,
				_.SUMW7,
				_.SUMJ1,
				_.SUMJ2,
				_.SUMJ3,
				_.SUMJ4,
				_.SUMJ5,
				_.SUMJ6,
				_.SUMJ7,
				_.CURWEEK_DSC,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._REC_NO,
				this._ORG_NO,
				this._REC_STA,
				this._YEAR,
				this._CURWEEK,
				this._SUMWEEK,
				this._REC_USR,
				this._REC_CST,
				this._BEG_DTM,
				this._END_DTM,
				this._SUMFDWT,
				this._SUMACTWT,
				this._FSTUSR_ID,
				this._FSTUSR_DTM,
				this._LSTUSR_ID,
				this._LSTUSR_DTM,
				this._REC_ID,
				this._WK1,
				this._WK6,
				this._TUEW,
				this._WEDW,
				this._THUW,
				this._MONW,
				this._FIRW,
				this._SATW,
				this._SUNW,
				this._SUMW1,
				this._SUMW2,
				this._SUMW3,
				this._SUMW4,
				this._SUMW5,
				this._SUMW6,
				this._SUMW7,
				this._SUMJ1,
				this._SUMJ2,
				this._SUMJ3,
				this._SUMJ4,
				this._SUMJ5,
				this._SUMJ6,
				this._SUMJ7,
				this._CURWEEK_DSC,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "DCWTRECMST");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field REC_NO = new Field("REC_NO", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ORG_NO = new Field("ORG_NO", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field REC_STA = new Field("REC_STA", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field YEAR = new Field("YEAR", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CURWEEK = new Field("CURWEEK", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SUMWEEK = new Field("SUMWEEK", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field REC_USR = new Field("REC_USR", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field REC_CST = new Field("REC_CST", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BEG_DTM = new Field("BEG_DTM", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field END_DTM = new Field("END_DTM", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SUMFDWT = new Field("SUMFDWT", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SUMACTWT = new Field("SUMACTWT", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FSTUSR_ID = new Field("FSTUSR_ID", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FSTUSR_DTM = new Field("FSTUSR_DTM", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LSTUSR_ID = new Field("LSTUSR_ID", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LSTUSR_DTM = new Field("LSTUSR_DTM", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field REC_ID = new Field("REC_ID", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field WK1 = new Field("WK1", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field WK6 = new Field("WK6", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TUEW = new Field("TUEW", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field WEDW = new Field("WEDW", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field THUW = new Field("THUW", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MONW = new Field("MONW", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FIRW = new Field("FIRW", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SATW = new Field("SATW", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SUNW = new Field("SUNW", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SUMW1 = new Field("SUMW1", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SUMW2 = new Field("SUMW2", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SUMW3 = new Field("SUMW3", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SUMW4 = new Field("SUMW4", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SUMW5 = new Field("SUMW5", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SUMW6 = new Field("SUMW6", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SUMW7 = new Field("SUMW7", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SUMJ1 = new Field("SUMJ1", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SUMJ2 = new Field("SUMJ2", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SUMJ3 = new Field("SUMJ3", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SUMJ4 = new Field("SUMJ4", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SUMJ5 = new Field("SUMJ5", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SUMJ6 = new Field("SUMJ6", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SUMJ7 = new Field("SUMJ7", "DCWTRECMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CURWEEK_DSC = new Field("CURWEEK_DSC", "DCWTRECMST", "");
		}
		#endregion
	}
}