//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Power.SPMEMS.Services
{
	/// <summary>
	/// 实体类NPS_BID_Integrated。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("NPS_BID_Integrated")]
	[Serializable]
	public partial class NPS_BID_Integrated : Entity
	{
		#region Model
		private Guid _ID;
		private string _Code;
		private string _Title;
		private string _ReportUnit;
		private string _ProjectDep;
		private string _AdditionalQua;
		private string _Submit;
		private string _Professional;
		private DateTime? _ReceiveDate;
		private string _MaterialCode;
		private DateTime? _MaterialDate;
		private string _BasicMemo;
		private DateTime? _ERPPushDate;
		private string _SPMNum;
		private string _SPMContract;
		private string _SpmMemo;
		private string _Demand;
		private string _Finish;
		private string _SinceCode;
		private string _EngineerNum;
		private float? _EndRate;
		private DateTime? _EndDate;
		private string _ReportUnitCode;
		private Guid? _RegHumIdCode;
		private string _RegHumNameCode;
		private DateTime? _RegDateCode;
		private string _TableName;
		private Guid? _BizAreaId;
		private int? _Sequ;
		private int? _Status;
		private Guid? _RegHumId;
		private string _RegHumName;
		private DateTime? _RegDate;
		private Guid? _RegPosiId;
		private Guid? _RegDeptId;
		private Guid? _EpsProjId;
		private Guid? _RecycleHumId;
		private Guid? _UpdHumId;
		private string _UpdHumName;
		private DateTime? _UpdDate;
		private Guid? _ApprHumId;
		private string _ApprHumName;
		private DateTime? _ApprDate;
		private string _Remark;
		private Guid? _OwnProjId;
		private string _OwnProjName;
		private string _EpsProjCode;
		private string _EpsProjName;
		private Guid? _CompanyID;
		private string _CompanyCode;
		private string _CompanyName;
		private string _FormType;
		private string _NoFinishMemo;
		private string _CompareHumName;
		private string _CompareHumCode;
		private DateTime? _CompareDate;
		private string _SumDesignNo;
		private string _SumVersion;
		private string _SumRequestName;
		private string _SumRequestVersion;
		private string _SPMCode;
		private string _LastHumOneName;
		private string _LastHumOneCode;
		private Guid? _LastHumOneID;
		private string _LastHumTwoName;
		private string _LastHumTwoCode;
		private Guid? _LastHumTwoID;
		private DateTime? _LastRegOneDate;
		private DateTime? _LastRegTwoDate;
		private string _WriteFinish;
		private string _IsHaveChange;

		/// <summary>
		/// 主键
		/// </summary>
		[Field("ID")]
		public Guid ID
		{
			get { return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 编号
		/// </summary>
		[Field("Code")]
		public string Code
		{
			get { return _Code; }
			set
			{
				this.OnPropertyValueChange("Code");
				this._Code = value;
			}
		}
		/// <summary>
		/// 标题
		/// </summary>
		[Field("Title")]
		public string Title
		{
			get { return _Title; }
			set
			{
				this.OnPropertyValueChange("Title");
				this._Title = value;
			}
		}
		/// <summary>
		/// 填报单位
		/// </summary>
		[Field("ReportUnit")]
		public string ReportUnit
		{
			get { return _ReportUnit; }
			set
			{
				this.OnPropertyValueChange("ReportUnit");
				this._ReportUnit = value;
			}
		}
		/// <summary>
		/// 所属项目部
		/// </summary>
		[Field("ProjectDep")]
		public string ProjectDep
		{
			get { return _ProjectDep; }
			set
			{
				this.OnPropertyValueChange("ProjectDep");
				this._ProjectDep = value;
			}
		}
		/// <summary>
		/// 主项
		/// </summary>
		[Field("AdditionalQua")]
		public string AdditionalQua
		{
			get { return _AdditionalQua; }
			set
			{
				this.OnPropertyValueChange("AdditionalQua");
				this._AdditionalQua = value;
			}
		}
		/// <summary>
		/// 提交人
		/// </summary>
		[Field("Submit")]
		public string Submit
		{
			get { return _Submit; }
			set
			{
				this.OnPropertyValueChange("Submit");
				this._Submit = value;
			}
		}
		/// <summary>
		/// 专业
		/// </summary>
		[Field("Professional")]
		public string Professional
		{
			get { return _Professional; }
			set
			{
				this.OnPropertyValueChange("Professional");
				this._Professional = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ReceiveDate")]
		public DateTime? ReceiveDate
		{
			get { return _ReceiveDate; }
			set
			{
				this.OnPropertyValueChange("ReceiveDate");
				this._ReceiveDate = value;
			}
		}
		/// <summary>
		/// 材料编码是否齐全
		/// </summary>
		[Field("MaterialCode")]
		public string MaterialCode
		{
			get { return _MaterialCode; }
			set
			{
				this.OnPropertyValueChange("MaterialCode");
				this._MaterialCode = value;
			}
		}
		/// <summary>
		/// 材料编码完成时间
		/// </summary>
		[Field("MaterialDate")]
		public DateTime? MaterialDate
		{
			get { return _MaterialDate; }
			set
			{
				this.OnPropertyValueChange("MaterialDate");
				this._MaterialDate = value;
			}
		}
		/// <summary>
		/// 基础备注
		/// </summary>
		[Field("BasicMemo")]
		public string BasicMemo
		{
			get { return _BasicMemo; }
			set
			{
				this.OnPropertyValueChange("BasicMemo");
				this._BasicMemo = value;
			}
		}
		/// <summary>
		/// 推送ERP时间
		/// </summary>
		[Field("ERPPushDate")]
		public DateTime? ERPPushDate
		{
			get { return _ERPPushDate; }
			set
			{
				this.OnPropertyValueChange("ERPPushDate");
				this._ERPPushDate = value;
			}
		}
		/// <summary>
		/// SPM请购号
		/// </summary>
		[Field("SPMNum")]
		public string SPMNum
		{
			get { return _SPMNum; }
			set
			{
				this.OnPropertyValueChange("SPMNum");
				this._SPMNum = value;
			}
		}
		/// <summary>
		/// 是否完成SPM合同
		/// </summary>
		[Field("SPMContract")]
		public string SPMContract
		{
			get { return _SPMContract; }
			set
			{
				this.OnPropertyValueChange("SPMContract");
				this._SPMContract = value;
			}
		}
		/// <summary>
		/// Spm备注
		/// </summary>
		[Field("SpmMemo")]
		public string SpmMemo
		{
			get { return _SpmMemo; }
			set
			{
				this.OnPropertyValueChange("SpmMemo");
				this._SpmMemo = value;
			}
		}
		/// <summary>
		/// 需求量
		/// </summary>
		[Field("Demand")]
		public string Demand
		{
			get { return _Demand; }
			set
			{
				this.OnPropertyValueChange("Demand");
				this._Demand = value;
			}
		}
		/// <summary>
		/// 完成
		/// </summary>
		[Field("Finish")]
		public string Finish
		{
			get { return _Finish; }
			set
			{
				this.OnPropertyValueChange("Finish");
				this._Finish = value;
			}
		}
		/// <summary>
		/// 自编码
		/// </summary>
		[Field("SinceCode")]
		public string SinceCode
		{
			get { return _SinceCode; }
			set
			{
				this.OnPropertyValueChange("SinceCode");
				this._SinceCode = value;
			}
		}
		/// <summary>
		/// 工程统一材料编码
		/// </summary>
		[Field("EngineerNum")]
		public string EngineerNum
		{
			get { return _EngineerNum; }
			set
			{
				this.OnPropertyValueChange("EngineerNum");
				this._EngineerNum = value;
			}
		}
		/// <summary>
		/// 完成比例
		/// </summary>
		[Field("EndRate")]
		public float? EndRate
		{
			get { return _EndRate; }
			set
			{
				this.OnPropertyValueChange("EndRate");
				this._EndRate = value;
			}
		}
		/// <summary>
		/// 完成时间
		/// </summary>
		[Field("EndDate")]
		public DateTime? EndDate
		{
			get { return _EndDate; }
			set
			{
				this.OnPropertyValueChange("EndDate");
				this._EndDate = value;
			}
		}
		/// <summary>
		/// 基础编码填报单位
		/// </summary>
		[Field("ReportUnitCode")]
		public string ReportUnitCode
		{
			get { return _ReportUnitCode; }
			set
			{
				this.OnPropertyValueChange("ReportUnitCode");
				this._ReportUnitCode = value;
			}
		}
		/// <summary>
		/// 基础编码录入人Id
		/// </summary>
		[Field("RegHumIdCode")]
		public Guid? RegHumIdCode
		{
			get { return _RegHumIdCode; }
			set
			{
				this.OnPropertyValueChange("RegHumIdCode");
				this._RegHumIdCode = value;
			}
		}
		/// <summary>
		/// 基础编码录入人名称
		/// </summary>
		[Field("RegHumNameCode")]
		public string RegHumNameCode
		{
			get { return _RegHumNameCode; }
			set
			{
				this.OnPropertyValueChange("RegHumNameCode");
				this._RegHumNameCode = value;
			}
		}
		/// <summary>
		/// 基础编码录入日期
		/// </summary>
		[Field("RegDateCode")]
		public DateTime? RegDateCode
		{
			get { return _RegDateCode; }
			set
			{
				this.OnPropertyValueChange("RegDateCode");
				this._RegDateCode = value;
			}
		}
		/// <summary>
		/// 数据所属表名
		/// </summary>
		[Field("TableName")]
		public string TableName
		{
			get { return _TableName; }
			set
			{
				this.OnPropertyValueChange("TableName");
				this._TableName = value;
			}
		}
		/// <summary>
		/// 数据录入业务域Id
		/// </summary>
		[Field("BizAreaId")]
		public Guid? BizAreaId
		{
			get { return _BizAreaId; }
			set
			{
				this.OnPropertyValueChange("BizAreaId");
				this._BizAreaId = value;
			}
		}
		/// <summary>
		/// 序号
		/// </summary>
		[Field("Sequ")]
		public int? Sequ
		{
			get { return _Sequ; }
			set
			{
				this.OnPropertyValueChange("Sequ");
				this._Sequ = value;
			}
		}
		/// <summary>
		/// 表单状态
		/// </summary>
		[Field("Status")]
		public int? Status
		{
			get { return _Status; }
			set
			{
				this.OnPropertyValueChange("Status");
				this._Status = value;
			}
		}
		/// <summary>
		/// 录入人Id
		/// </summary>
		[Field("RegHumId")]
		public Guid? RegHumId
		{
			get { return _RegHumId; }
			set
			{
				this.OnPropertyValueChange("RegHumId");
				this._RegHumId = value;
			}
		}
		/// <summary>
		/// 录入人名称
		/// </summary>
		[Field("RegHumName")]
		public string RegHumName
		{
			get { return _RegHumName; }
			set
			{
				this.OnPropertyValueChange("RegHumName");
				this._RegHumName = value;
			}
		}
		/// <summary>
		/// 录入日期
		/// </summary>
		[Field("RegDate")]
		public DateTime? RegDate
		{
			get { return _RegDate; }
			set
			{
				this.OnPropertyValueChange("RegDate");
				this._RegDate = value;
			}
		}
		/// <summary>
		/// 录入人岗位Id
		/// </summary>
		[Field("RegPosiId")]
		public Guid? RegPosiId
		{
			get { return _RegPosiId; }
			set
			{
				this.OnPropertyValueChange("RegPosiId");
				this._RegPosiId = value;
			}
		}
		/// <summary>
		/// 录入人部门Id
		/// </summary>
		[Field("RegDeptId")]
		public Guid? RegDeptId
		{
			get { return _RegDeptId; }
			set
			{
				this.OnPropertyValueChange("RegDeptId");
				this._RegDeptId = value;
			}
		}
		/// <summary>
		/// 记录所属EPS节点Id
		/// </summary>
		[Field("EpsProjId")]
		public Guid? EpsProjId
		{
			get { return _EpsProjId; }
			set
			{
				this.OnPropertyValueChange("EpsProjId");
				this._EpsProjId = value;
			}
		}
		/// <summary>
		/// 删除人Id
		/// </summary>
		[Field("RecycleHumId")]
		public Guid? RecycleHumId
		{
			get { return _RecycleHumId; }
			set
			{
				this.OnPropertyValueChange("RecycleHumId");
				this._RecycleHumId = value;
			}
		}
		/// <summary>
		/// 最后更新人Id
		/// </summary>
		[Field("UpdHumId")]
		public Guid? UpdHumId
		{
			get { return _UpdHumId; }
			set
			{
				this.OnPropertyValueChange("UpdHumId");
				this._UpdHumId = value;
			}
		}
		/// <summary>
		/// 最后更新人名称
		/// </summary>
		[Field("UpdHumName")]
		public string UpdHumName
		{
			get { return _UpdHumName; }
			set
			{
				this.OnPropertyValueChange("UpdHumName");
				this._UpdHumName = value;
			}
		}
		/// <summary>
		/// 最后更新日期
		/// </summary>
		[Field("UpdDate")]
		public DateTime? UpdDate
		{
			get { return _UpdDate; }
			set
			{
				this.OnPropertyValueChange("UpdDate");
				this._UpdDate = value;
			}
		}
		/// <summary>
		/// 批准人Id
		/// </summary>
		[Field("ApprHumId")]
		public Guid? ApprHumId
		{
			get { return _ApprHumId; }
			set
			{
				this.OnPropertyValueChange("ApprHumId");
				this._ApprHumId = value;
			}
		}
		/// <summary>
		/// 批准人名称
		/// </summary>
		[Field("ApprHumName")]
		public string ApprHumName
		{
			get { return _ApprHumName; }
			set
			{
				this.OnPropertyValueChange("ApprHumName");
				this._ApprHumName = value;
			}
		}
		/// <summary>
		/// 批准日期
		/// </summary>
		[Field("ApprDate")]
		public DateTime? ApprDate
		{
			get { return _ApprDate; }
			set
			{
				this.OnPropertyValueChange("ApprDate");
				this._ApprDate = value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get { return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 所属项目Id
		/// </summary>
		[Field("OwnProjId")]
		public Guid? OwnProjId
		{
			get { return _OwnProjId; }
			set
			{
				this.OnPropertyValueChange("OwnProjId");
				this._OwnProjId = value;
			}
		}
		/// <summary>
		/// 管理层级名称
		/// </summary>
		[Field("OwnProjName")]
		public string OwnProjName
		{
			get { return _OwnProjName; }
			set
			{
				this.OnPropertyValueChange("OwnProjName");
				this._OwnProjName = value;
			}
		}
		/// <summary>
		/// EPS编号
		/// </summary>
		[Field("EpsProjCode")]
		public string EpsProjCode
		{
			get { return _EpsProjCode; }
			set
			{
				this.OnPropertyValueChange("EpsProjCode");
				this._EpsProjCode = value;
			}
		}
		/// <summary>
		/// EPS名称
		/// </summary>
		[Field("EpsProjName")]
		public string EpsProjName
		{
			get { return _EpsProjName; }
			set
			{
				this.OnPropertyValueChange("EpsProjName");
				this._EpsProjName = value;
			}
		}
		/// <summary>
		/// 单位ID
		/// </summary>
		[Field("CompanyID")]
		public Guid? CompanyID
		{
			get { return _CompanyID; }
			set
			{
				this.OnPropertyValueChange("CompanyID");
				this._CompanyID = value;
			}
		}
		/// <summary>
		/// 单位编号
		/// </summary>
		[Field("CompanyCode")]
		public string CompanyCode
		{
			get { return _CompanyCode; }
			set
			{
				this.OnPropertyValueChange("CompanyCode");
				this._CompanyCode = value;
			}
		}
		/// <summary>
		/// 单位名称
		/// </summary>
		[Field("CompanyName")]
		public string CompanyName
		{
			get { return _CompanyName; }
			set
			{
				this.OnPropertyValueChange("CompanyName");
				this._CompanyName = value;
			}
		}
		/// <summary>
		/// 物资类别
		/// </summary>
		[Field("FormType")]
		public string FormType
		{
			get { return _FormType; }
			set
			{
				this.OnPropertyValueChange("FormType");
				this._FormType = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("NoFinishMemo")]
		public string NoFinishMemo
		{
			get { return _NoFinishMemo; }
			set
			{
				this.OnPropertyValueChange("NoFinishMemo");
				this._NoFinishMemo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CompareHumName")]
		public string CompareHumName
		{
			get { return _CompareHumName; }
			set
			{
				this.OnPropertyValueChange("CompareHumName");
				this._CompareHumName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CompareHumCode")]
		public string CompareHumCode
		{
			get { return _CompareHumCode; }
			set
			{
				this.OnPropertyValueChange("CompareHumCode");
				this._CompareHumCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CompareDate")]
		public DateTime? CompareDate
		{
			get { return _CompareDate; }
			set
			{
				this.OnPropertyValueChange("CompareDate");
				this._CompareDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SumDesignNo")]
		public string SumDesignNo
		{
			get { return _SumDesignNo; }
			set
			{
				this.OnPropertyValueChange("SumDesignNo");
				this._SumDesignNo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SumVersion")]
		public string SumVersion
		{
			get { return _SumVersion; }
			set
			{
				this.OnPropertyValueChange("SumVersion");
				this._SumVersion = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SumRequestName")]
		public string SumRequestName
		{
			get { return _SumRequestName; }
			set
			{
				this.OnPropertyValueChange("SumRequestName");
				this._SumRequestName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SumRequestVersion")]
		public string SumRequestVersion
		{
			get { return _SumRequestVersion; }
			set
			{
				this.OnPropertyValueChange("SumRequestVersion");
				this._SumRequestVersion = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SPMCode")]
		public string SPMCode
		{
			get { return _SPMCode; }
			set
			{
				this.OnPropertyValueChange("SPMCode");
				this._SPMCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LastHumOneName")]
		public string LastHumOneName
		{
			get { return _LastHumOneName; }
			set
			{
				this.OnPropertyValueChange("LastHumOneName");
				this._LastHumOneName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LastHumOneCode")]
		public string LastHumOneCode
		{
			get { return _LastHumOneCode; }
			set
			{
				this.OnPropertyValueChange("LastHumOneCode");
				this._LastHumOneCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LastHumOneID")]
		public Guid? LastHumOneID
		{
			get { return _LastHumOneID; }
			set
			{
				this.OnPropertyValueChange("LastHumOneID");
				this._LastHumOneID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LastHumTwoName")]
		public string LastHumTwoName
		{
			get { return _LastHumTwoName; }
			set
			{
				this.OnPropertyValueChange("LastHumTwoName");
				this._LastHumTwoName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LastHumTwoCode")]
		public string LastHumTwoCode
		{
			get { return _LastHumTwoCode; }
			set
			{
				this.OnPropertyValueChange("LastHumTwoCode");
				this._LastHumTwoCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LastHumTwoID")]
		public Guid? LastHumTwoID
		{
			get { return _LastHumTwoID; }
			set
			{
				this.OnPropertyValueChange("LastHumTwoID");
				this._LastHumTwoID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LastRegOneDate")]
		public DateTime? LastRegOneDate
		{
			get { return _LastRegOneDate; }
			set
			{
				this.OnPropertyValueChange("LastRegOneDate");
				this._LastRegOneDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LastRegTwoDate")]
		public DateTime? LastRegTwoDate
		{
			get { return _LastRegTwoDate; }
			set
			{
				this.OnPropertyValueChange("LastRegTwoDate");
				this._LastRegTwoDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("WriteFinish")]
		public string WriteFinish
		{
			get { return _WriteFinish; }
			set
			{
				this.OnPropertyValueChange("WriteFinish");
				this._WriteFinish = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("IsHaveChange")]
		public string IsHaveChange
		{
			get { return _IsHaveChange; }
			set
			{
				this.OnPropertyValueChange("IsHaveChange");
				this._IsHaveChange = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.Code,
				_.Title,
				_.ReportUnit,
				_.ProjectDep,
				_.AdditionalQua,
				_.Submit,
				_.Professional,
				_.ReceiveDate,
				_.MaterialCode,
				_.MaterialDate,
				_.BasicMemo,
				_.ERPPushDate,
				_.SPMNum,
				_.SPMContract,
				_.SpmMemo,
				_.Demand,
				_.Finish,
				_.SinceCode,
				_.EngineerNum,
				_.EndRate,
				_.EndDate,
				_.ReportUnitCode,
				_.RegHumIdCode,
				_.RegHumNameCode,
				_.RegDateCode,
				_.TableName,
				_.BizAreaId,
				_.Sequ,
				_.Status,
				_.RegHumId,
				_.RegHumName,
				_.RegDate,
				_.RegPosiId,
				_.RegDeptId,
				_.EpsProjId,
				_.RecycleHumId,
				_.UpdHumId,
				_.UpdHumName,
				_.UpdDate,
				_.ApprHumId,
				_.ApprHumName,
				_.ApprDate,
				_.Remark,
				_.OwnProjId,
				_.OwnProjName,
				_.EpsProjCode,
				_.EpsProjName,
				_.CompanyID,
				_.CompanyCode,
				_.CompanyName,
				_.FormType,
				_.NoFinishMemo,
				_.CompareHumName,
				_.CompareHumCode,
				_.CompareDate,
				_.SumDesignNo,
				_.SumVersion,
				_.SumRequestName,
				_.SumRequestVersion,
				_.SPMCode,
				_.LastHumOneName,
				_.LastHumOneCode,
				_.LastHumOneID,
				_.LastHumTwoName,
				_.LastHumTwoCode,
				_.LastHumTwoID,
				_.LastRegOneDate,
				_.LastRegTwoDate,
				_.WriteFinish,
				_.IsHaveChange,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._Code,
				this._Title,
				this._ReportUnit,
				this._ProjectDep,
				this._AdditionalQua,
				this._Submit,
				this._Professional,
				this._ReceiveDate,
				this._MaterialCode,
				this._MaterialDate,
				this._BasicMemo,
				this._ERPPushDate,
				this._SPMNum,
				this._SPMContract,
				this._SpmMemo,
				this._Demand,
				this._Finish,
				this._SinceCode,
				this._EngineerNum,
				this._EndRate,
				this._EndDate,
				this._ReportUnitCode,
				this._RegHumIdCode,
				this._RegHumNameCode,
				this._RegDateCode,
				this._TableName,
				this._BizAreaId,
				this._Sequ,
				this._Status,
				this._RegHumId,
				this._RegHumName,
				this._RegDate,
				this._RegPosiId,
				this._RegDeptId,
				this._EpsProjId,
				this._RecycleHumId,
				this._UpdHumId,
				this._UpdHumName,
				this._UpdDate,
				this._ApprHumId,
				this._ApprHumName,
				this._ApprDate,
				this._Remark,
				this._OwnProjId,
				this._OwnProjName,
				this._EpsProjCode,
				this._EpsProjName,
				this._CompanyID,
				this._CompanyCode,
				this._CompanyName,
				this._FormType,
				this._NoFinishMemo,
				this._CompareHumName,
				this._CompareHumCode,
				this._CompareDate,
				this._SumDesignNo,
				this._SumVersion,
				this._SumRequestName,
				this._SumRequestVersion,
				this._SPMCode,
				this._LastHumOneName,
				this._LastHumOneCode,
				this._LastHumOneID,
				this._LastHumTwoName,
				this._LastHumTwoCode,
				this._LastHumTwoID,
				this._LastRegOneDate,
				this._LastRegTwoDate,
				this._WriteFinish,
				this._IsHaveChange,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "NPS_BID_Integrated");
			/// <summary>
			/// 主键
			/// </summary>
			public readonly static Field ID = new Field("ID", "NPS_BID_Integrated", "主键");
			/// <summary>
			/// 编号
			/// </summary>
			public readonly static Field Code = new Field("Code", "NPS_BID_Integrated", "编号");
			/// <summary>
			/// 标题
			/// </summary>
			public readonly static Field Title = new Field("Title", "NPS_BID_Integrated", "标题");
			/// <summary>
			/// 填报单位
			/// </summary>
			public readonly static Field ReportUnit = new Field("ReportUnit", "NPS_BID_Integrated", "填报单位");
			/// <summary>
			/// 所属项目部
			/// </summary>
			public readonly static Field ProjectDep = new Field("ProjectDep", "NPS_BID_Integrated", "所属项目部");
			/// <summary>
			/// 主项
			/// </summary>
			public readonly static Field AdditionalQua = new Field("AdditionalQua", "NPS_BID_Integrated", "主项");
			/// <summary>
			/// 提交人
			/// </summary>
			public readonly static Field Submit = new Field("Submit", "NPS_BID_Integrated", "提交人");
			/// <summary>
			/// 专业
			/// </summary>
			public readonly static Field Professional = new Field("Professional", "NPS_BID_Integrated", "专业");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ReceiveDate = new Field("ReceiveDate", "NPS_BID_Integrated", "");
			/// <summary>
			/// 材料编码是否齐全
			/// </summary>
			public readonly static Field MaterialCode = new Field("MaterialCode", "NPS_BID_Integrated", "材料编码是否齐全");
			/// <summary>
			/// 材料编码完成时间
			/// </summary>
			public readonly static Field MaterialDate = new Field("MaterialDate", "NPS_BID_Integrated", "材料编码完成时间");
			/// <summary>
			/// 基础备注
			/// </summary>
			public readonly static Field BasicMemo = new Field("BasicMemo", "NPS_BID_Integrated", "基础备注");
			/// <summary>
			/// 推送ERP时间
			/// </summary>
			public readonly static Field ERPPushDate = new Field("ERPPushDate", "NPS_BID_Integrated", "推送ERP时间");
			/// <summary>
			/// SPM请购号
			/// </summary>
			public readonly static Field SPMNum = new Field("SPMNum", "NPS_BID_Integrated", "SPM请购号");
			/// <summary>
			/// 是否完成SPM合同
			/// </summary>
			public readonly static Field SPMContract = new Field("SPMContract", "NPS_BID_Integrated", "是否完成SPM合同");
			/// <summary>
			/// Spm备注
			/// </summary>
			public readonly static Field SpmMemo = new Field("SpmMemo", "NPS_BID_Integrated", "Spm备注");
			/// <summary>
			/// 需求量
			/// </summary>
			public readonly static Field Demand = new Field("Demand", "NPS_BID_Integrated", "需求量");
			/// <summary>
			/// 完成
			/// </summary>
			public readonly static Field Finish = new Field("Finish", "NPS_BID_Integrated", "完成");
			/// <summary>
			/// 自编码
			/// </summary>
			public readonly static Field SinceCode = new Field("SinceCode", "NPS_BID_Integrated", "自编码");
			/// <summary>
			/// 工程统一材料编码
			/// </summary>
			public readonly static Field EngineerNum = new Field("EngineerNum", "NPS_BID_Integrated", "工程统一材料编码");
			/// <summary>
			/// 完成比例
			/// </summary>
			public readonly static Field EndRate = new Field("EndRate", "NPS_BID_Integrated", "完成比例");
			/// <summary>
			/// 完成时间
			/// </summary>
			public readonly static Field EndDate = new Field("EndDate", "NPS_BID_Integrated", "完成时间");
			/// <summary>
			/// 基础编码填报单位
			/// </summary>
			public readonly static Field ReportUnitCode = new Field("ReportUnitCode", "NPS_BID_Integrated", "基础编码填报单位");
			/// <summary>
			/// 基础编码录入人Id
			/// </summary>
			public readonly static Field RegHumIdCode = new Field("RegHumIdCode", "NPS_BID_Integrated", "基础编码录入人Id");
			/// <summary>
			/// 基础编码录入人名称
			/// </summary>
			public readonly static Field RegHumNameCode = new Field("RegHumNameCode", "NPS_BID_Integrated", "基础编码录入人名称");
			/// <summary>
			/// 基础编码录入日期
			/// </summary>
			public readonly static Field RegDateCode = new Field("RegDateCode", "NPS_BID_Integrated", "基础编码录入日期");
			/// <summary>
			/// 数据所属表名
			/// </summary>
			public readonly static Field TableName = new Field("TableName", "NPS_BID_Integrated", "数据所属表名");
			/// <summary>
			/// 数据录入业务域Id
			/// </summary>
			public readonly static Field BizAreaId = new Field("BizAreaId", "NPS_BID_Integrated", "数据录入业务域Id");
			/// <summary>
			/// 序号
			/// </summary>
			public readonly static Field Sequ = new Field("Sequ", "NPS_BID_Integrated", "序号");
			/// <summary>
			/// 表单状态
			/// </summary>
			public readonly static Field Status = new Field("Status", "NPS_BID_Integrated", "表单状态");
			/// <summary>
			/// 录入人Id
			/// </summary>
			public readonly static Field RegHumId = new Field("RegHumId", "NPS_BID_Integrated", "录入人Id");
			/// <summary>
			/// 录入人名称
			/// </summary>
			public readonly static Field RegHumName = new Field("RegHumName", "NPS_BID_Integrated", "录入人名称");
			/// <summary>
			/// 录入日期
			/// </summary>
			public readonly static Field RegDate = new Field("RegDate", "NPS_BID_Integrated", "录入日期");
			/// <summary>
			/// 录入人岗位Id
			/// </summary>
			public readonly static Field RegPosiId = new Field("RegPosiId", "NPS_BID_Integrated", "录入人岗位Id");
			/// <summary>
			/// 录入人部门Id
			/// </summary>
			public readonly static Field RegDeptId = new Field("RegDeptId", "NPS_BID_Integrated", "录入人部门Id");
			/// <summary>
			/// 记录所属EPS节点Id
			/// </summary>
			public readonly static Field EpsProjId = new Field("EpsProjId", "NPS_BID_Integrated", "记录所属EPS节点Id");
			/// <summary>
			/// 删除人Id
			/// </summary>
			public readonly static Field RecycleHumId = new Field("RecycleHumId", "NPS_BID_Integrated", "删除人Id");
			/// <summary>
			/// 最后更新人Id
			/// </summary>
			public readonly static Field UpdHumId = new Field("UpdHumId", "NPS_BID_Integrated", "最后更新人Id");
			/// <summary>
			/// 最后更新人名称
			/// </summary>
			public readonly static Field UpdHumName = new Field("UpdHumName", "NPS_BID_Integrated", "最后更新人名称");
			/// <summary>
			/// 最后更新日期
			/// </summary>
			public readonly static Field UpdDate = new Field("UpdDate", "NPS_BID_Integrated", "最后更新日期");
			/// <summary>
			/// 批准人Id
			/// </summary>
			public readonly static Field ApprHumId = new Field("ApprHumId", "NPS_BID_Integrated", "批准人Id");
			/// <summary>
			/// 批准人名称
			/// </summary>
			public readonly static Field ApprHumName = new Field("ApprHumName", "NPS_BID_Integrated", "批准人名称");
			/// <summary>
			/// 批准日期
			/// </summary>
			public readonly static Field ApprDate = new Field("ApprDate", "NPS_BID_Integrated", "批准日期");
			/// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "NPS_BID_Integrated", "备注");
			/// <summary>
			/// 所属项目Id
			/// </summary>
			public readonly static Field OwnProjId = new Field("OwnProjId", "NPS_BID_Integrated", "所属项目Id");
			/// <summary>
			/// 管理层级名称
			/// </summary>
			public readonly static Field OwnProjName = new Field("OwnProjName", "NPS_BID_Integrated", "管理层级名称");
			/// <summary>
			/// EPS编号
			/// </summary>
			public readonly static Field EpsProjCode = new Field("EpsProjCode", "NPS_BID_Integrated", "EPS编号");
			/// <summary>
			/// EPS名称
			/// </summary>
			public readonly static Field EpsProjName = new Field("EpsProjName", "NPS_BID_Integrated", "EPS名称");
			/// <summary>
			/// 单位ID
			/// </summary>
			public readonly static Field CompanyID = new Field("CompanyID", "NPS_BID_Integrated", "单位ID");
			/// <summary>
			/// 单位编号
			/// </summary>
			public readonly static Field CompanyCode = new Field("CompanyCode", "NPS_BID_Integrated", "单位编号");
			/// <summary>
			/// 单位名称
			/// </summary>
			public readonly static Field CompanyName = new Field("CompanyName", "NPS_BID_Integrated", "单位名称");
			/// <summary>
			/// 物资类别
			/// </summary>
			public readonly static Field FormType = new Field("FormType", "NPS_BID_Integrated", "物资类别");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field NoFinishMemo = new Field("NoFinishMemo", "NPS_BID_Integrated", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CompareHumName = new Field("CompareHumName", "NPS_BID_Integrated", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CompareHumCode = new Field("CompareHumCode", "NPS_BID_Integrated", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CompareDate = new Field("CompareDate", "NPS_BID_Integrated", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SumDesignNo = new Field("SumDesignNo", "NPS_BID_Integrated", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SumVersion = new Field("SumVersion", "NPS_BID_Integrated", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SumRequestName = new Field("SumRequestName", "NPS_BID_Integrated", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SumRequestVersion = new Field("SumRequestVersion", "NPS_BID_Integrated", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SPMCode = new Field("SPMCode", "NPS_BID_Integrated", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastHumOneName = new Field("LastHumOneName", "NPS_BID_Integrated", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastHumOneCode = new Field("LastHumOneCode", "NPS_BID_Integrated", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastHumOneID = new Field("LastHumOneID", "NPS_BID_Integrated", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastHumTwoName = new Field("LastHumTwoName", "NPS_BID_Integrated", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastHumTwoCode = new Field("LastHumTwoCode", "NPS_BID_Integrated", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastHumTwoID = new Field("LastHumTwoID", "NPS_BID_Integrated", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastRegOneDate = new Field("LastRegOneDate", "NPS_BID_Integrated", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastRegTwoDate = new Field("LastRegTwoDate", "NPS_BID_Integrated", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field WriteFinish = new Field("WriteFinish", "NPS_BID_Integrated", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsHaveChange = new Field("IsHaveChange", "NPS_BID_Integrated", "");
		}
		#endregion
	}
}