//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace Power.SPMEMS.Services.Models
{
	/// <summary>
	/// 实体类OGCRWMST。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("OGCRWMST")]
	[Serializable]
	[DataContract]
	public partial class OGCRWMST : Entity
	{
		#region Model
		private int _CRW_NO;
		private string _CRWVER_ID;
		private string _CRW_ID;
		private string _CRW_NAM;
		private int? _CRWUP_NO;
		private string _VALID_STA;
		private string _ACTOR_FLG;
		private int? _SHIFT_CNT;
		private int? _SKL_NO;
		private string _SCHED_ID;
		private int? _SIZE_CNT;
		private int? _TIMANCVAL_NO;
		private string _CRW_DSC;
		private DateTime? _BEGIN_DTM;
		private DateTime? _END_DTM;
		private string _FSTUSR_ID;
		private DateTime? _FSTUSR_DTM;
		private string _LSTUSR_ID;
		private DateTime? _LSTUSR_DTM;

		/// <summary>
		/// 
		/// </summary>
		[Field("CRW_NO")]
		[DataMember]
		public int CRW_NO
		{
			get { return _CRW_NO; }
			set
			{
				this.OnPropertyValueChange("CRW_NO");
				this._CRW_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CRWVER_ID")]
		[DataMember]
		public string CRWVER_ID
		{
			get { return _CRWVER_ID; }
			set
			{
				this.OnPropertyValueChange("CRWVER_ID");
				this._CRWVER_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CRW_ID")]
		[DataMember]
		public string CRW_ID
		{
			get { return _CRW_ID; }
			set
			{
				this.OnPropertyValueChange("CRW_ID");
				this._CRW_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CRW_NAM")]
		[DataMember]
		public string CRW_NAM
		{
			get { return _CRW_NAM; }
			set
			{
				this.OnPropertyValueChange("CRW_NAM");
				this._CRW_NAM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CRWUP_NO")]
		[DataMember]
		public int? CRWUP_NO
		{
			get { return _CRWUP_NO; }
			set
			{
				this.OnPropertyValueChange("CRWUP_NO");
				this._CRWUP_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("VALID_STA")]
		[DataMember]
		public string VALID_STA
		{
			get { return _VALID_STA; }
			set
			{
				this.OnPropertyValueChange("VALID_STA");
				this._VALID_STA = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ACTOR_FLG")]
		[DataMember]
		public string ACTOR_FLG
		{
			get { return _ACTOR_FLG; }
			set
			{
				this.OnPropertyValueChange("ACTOR_FLG");
				this._ACTOR_FLG = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SHIFT_CNT")]
		[DataMember]
		public int? SHIFT_CNT
		{
			get { return _SHIFT_CNT; }
			set
			{
				this.OnPropertyValueChange("SHIFT_CNT");
				this._SHIFT_CNT = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SKL_NO")]
		[DataMember]
		public int? SKL_NO
		{
			get { return _SKL_NO; }
			set
			{
				this.OnPropertyValueChange("SKL_NO");
				this._SKL_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SCHED_ID")]
		[DataMember]
		public string SCHED_ID
		{
			get { return _SCHED_ID; }
			set
			{
				this.OnPropertyValueChange("SCHED_ID");
				this._SCHED_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SIZE_CNT")]
		[DataMember]
		public int? SIZE_CNT
		{
			get { return _SIZE_CNT; }
			set
			{
				this.OnPropertyValueChange("SIZE_CNT");
				this._SIZE_CNT = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TIMANCVAL_NO")]
		[DataMember]
		public int? TIMANCVAL_NO
		{
			get { return _TIMANCVAL_NO; }
			set
			{
				this.OnPropertyValueChange("TIMANCVAL_NO");
				this._TIMANCVAL_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CRW_DSC")]
		[DataMember]
		public string CRW_DSC
		{
			get { return _CRW_DSC; }
			set
			{
				this.OnPropertyValueChange("CRW_DSC");
				this._CRW_DSC = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("BEGIN_DTM")]
		[DataMember]
		public DateTime? BEGIN_DTM
		{
			get { return _BEGIN_DTM; }
			set
			{
				this.OnPropertyValueChange("BEGIN_DTM");
				this._BEGIN_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("END_DTM")]
		[DataMember]
		public DateTime? END_DTM
		{
			get { return _END_DTM; }
			set
			{
				this.OnPropertyValueChange("END_DTM");
				this._END_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FSTUSR_ID")]
		[DataMember]
		public string FSTUSR_ID
		{
			get { return _FSTUSR_ID; }
			set
			{
				this.OnPropertyValueChange("FSTUSR_ID");
				this._FSTUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FSTUSR_DTM")]
		[DataMember]
		public DateTime? FSTUSR_DTM
		{
			get { return _FSTUSR_DTM; }
			set
			{
				this.OnPropertyValueChange("FSTUSR_DTM");
				this._FSTUSR_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LSTUSR_ID")]
		[DataMember]
		public string LSTUSR_ID
		{
			get { return _LSTUSR_ID; }
			set
			{
				this.OnPropertyValueChange("LSTUSR_ID");
				this._LSTUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LSTUSR_DTM")]
		[DataMember]
		public DateTime? LSTUSR_DTM
		{
			get { return _LSTUSR_DTM; }
			set
			{
				this.OnPropertyValueChange("LSTUSR_DTM");
				this._LSTUSR_DTM = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.CRW_NO,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.CRW_NO,
				_.CRWVER_ID,
				_.CRW_ID,
				_.CRW_NAM,
				_.CRWUP_NO,
				_.VALID_STA,
				_.ACTOR_FLG,
				_.SHIFT_CNT,
				_.SKL_NO,
				_.SCHED_ID,
				_.SIZE_CNT,
				_.TIMANCVAL_NO,
				_.CRW_DSC,
				_.BEGIN_DTM,
				_.END_DTM,
				_.FSTUSR_ID,
				_.FSTUSR_DTM,
				_.LSTUSR_ID,
				_.LSTUSR_DTM,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._CRW_NO,
				this._CRWVER_ID,
				this._CRW_ID,
				this._CRW_NAM,
				this._CRWUP_NO,
				this._VALID_STA,
				this._ACTOR_FLG,
				this._SHIFT_CNT,
				this._SKL_NO,
				this._SCHED_ID,
				this._SIZE_CNT,
				this._TIMANCVAL_NO,
				this._CRW_DSC,
				this._BEGIN_DTM,
				this._END_DTM,
				this._FSTUSR_ID,
				this._FSTUSR_DTM,
				this._LSTUSR_ID,
				this._LSTUSR_DTM,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "OGCRWMST");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CRW_NO = new Field("CRW_NO", "OGCRWMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CRWVER_ID = new Field("CRWVER_ID", "OGCRWMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CRW_ID = new Field("CRW_ID", "OGCRWMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CRW_NAM = new Field("CRW_NAM", "OGCRWMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CRWUP_NO = new Field("CRWUP_NO", "OGCRWMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field VALID_STA = new Field("VALID_STA", "OGCRWMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ACTOR_FLG = new Field("ACTOR_FLG", "OGCRWMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SHIFT_CNT = new Field("SHIFT_CNT", "OGCRWMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SKL_NO = new Field("SKL_NO", "OGCRWMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SCHED_ID = new Field("SCHED_ID", "OGCRWMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SIZE_CNT = new Field("SIZE_CNT", "OGCRWMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TIMANCVAL_NO = new Field("TIMANCVAL_NO", "OGCRWMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CRW_DSC = new Field("CRW_DSC", "OGCRWMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BEGIN_DTM = new Field("BEGIN_DTM", "OGCRWMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field END_DTM = new Field("END_DTM", "OGCRWMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FSTUSR_ID = new Field("FSTUSR_ID", "OGCRWMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FSTUSR_DTM = new Field("FSTUSR_DTM", "OGCRWMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LSTUSR_ID = new Field("LSTUSR_ID", "OGCRWMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LSTUSR_DTM = new Field("LSTUSR_DTM", "OGCRWMST", "");
		}
		#endregion
	}
}