//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace Power.SPMEMS.Services.Models
{
	/// <summary>
	/// 实体类OGCSTMST。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("OGCSTMST")]
	[Serializable]
	[DataContract]
	public partial class OGCSTMST : Entity
	{
		#region Model
		private int _CST_NO;
		private string _CSTVER_ID;
		private string _CST_ID;
		private string _CST_NAM;
		private int? _CSTUP_NO;
		private string _CSTTRN_FLG;
		private string _CST_TYP;
		private string _VALID_STA;
		private string _CST_DSC;
		private DateTime? _BEGIN_DTM;
		private DateTime? _END_DTM;
		private string _FSTUSR_ID;
		private DateTime? _FSTUSR_DTM;
		private string _LSTUSR_ID;
		private DateTime? _LSTUSR_DTM;
		private int? _MGREMP_NO;
		private int? _GLACHG_NO;
		private int? _GLALAB_NO;
		private string _ACC_NO;
		private int? _MOP_NO;
		private string _CRWVER_ID;
		private string _CW_FLG;
		private int? _ORG_NO;

		/// <summary>
		/// 
		/// </summary>
		[Field("CST_NO")]
		[DataMember]
		public int CST_NO
		{
			get { return _CST_NO; }
			set
			{
				this.OnPropertyValueChange("CST_NO");
				this._CST_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CSTVER_ID")]
		[DataMember]
		public string CSTVER_ID
		{
			get { return _CSTVER_ID; }
			set
			{
				this.OnPropertyValueChange("CSTVER_ID");
				this._CSTVER_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CST_ID")]
		[DataMember]
		public string CST_ID
		{
			get { return _CST_ID; }
			set
			{
				this.OnPropertyValueChange("CST_ID");
				this._CST_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CST_NAM")]
		[DataMember]
		public string CST_NAM
		{
			get { return _CST_NAM; }
			set
			{
				this.OnPropertyValueChange("CST_NAM");
				this._CST_NAM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CSTUP_NO")]
		[DataMember]
		public int? CSTUP_NO
		{
			get { return _CSTUP_NO; }
			set
			{
				this.OnPropertyValueChange("CSTUP_NO");
				this._CSTUP_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CSTTRN_FLG")]
		[DataMember]
		public string CSTTRN_FLG
		{
			get { return _CSTTRN_FLG; }
			set
			{
				this.OnPropertyValueChange("CSTTRN_FLG");
				this._CSTTRN_FLG = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CST_TYP")]
		[DataMember]
		public string CST_TYP
		{
			get { return _CST_TYP; }
			set
			{
				this.OnPropertyValueChange("CST_TYP");
				this._CST_TYP = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("VALID_STA")]
		[DataMember]
		public string VALID_STA
		{
			get { return _VALID_STA; }
			set
			{
				this.OnPropertyValueChange("VALID_STA");
				this._VALID_STA = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CST_DSC")]
		[DataMember]
		public string CST_DSC
		{
			get { return _CST_DSC; }
			set
			{
				this.OnPropertyValueChange("CST_DSC");
				this._CST_DSC = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("BEGIN_DTM")]
		[DataMember]
		public DateTime? BEGIN_DTM
		{
			get { return _BEGIN_DTM; }
			set
			{
				this.OnPropertyValueChange("BEGIN_DTM");
				this._BEGIN_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("END_DTM")]
		[DataMember]
		public DateTime? END_DTM
		{
			get { return _END_DTM; }
			set
			{
				this.OnPropertyValueChange("END_DTM");
				this._END_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FSTUSR_ID")]
		[DataMember]
		public string FSTUSR_ID
		{
			get { return _FSTUSR_ID; }
			set
			{
				this.OnPropertyValueChange("FSTUSR_ID");
				this._FSTUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FSTUSR_DTM")]
		[DataMember]
		public DateTime? FSTUSR_DTM
		{
			get { return _FSTUSR_DTM; }
			set
			{
				this.OnPropertyValueChange("FSTUSR_DTM");
				this._FSTUSR_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LSTUSR_ID")]
		[DataMember]
		public string LSTUSR_ID
		{
			get { return _LSTUSR_ID; }
			set
			{
				this.OnPropertyValueChange("LSTUSR_ID");
				this._LSTUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LSTUSR_DTM")]
		[DataMember]
		public DateTime? LSTUSR_DTM
		{
			get { return _LSTUSR_DTM; }
			set
			{
				this.OnPropertyValueChange("LSTUSR_DTM");
				this._LSTUSR_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MGREMP_NO")]
		[DataMember]
		public int? MGREMP_NO
		{
			get { return _MGREMP_NO; }
			set
			{
				this.OnPropertyValueChange("MGREMP_NO");
				this._MGREMP_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("GLACHG_NO")]
		[DataMember]
		public int? GLACHG_NO
		{
			get { return _GLACHG_NO; }
			set
			{
				this.OnPropertyValueChange("GLACHG_NO");
				this._GLACHG_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("GLALAB_NO")]
		[DataMember]
		public int? GLALAB_NO
		{
			get { return _GLALAB_NO; }
			set
			{
				this.OnPropertyValueChange("GLALAB_NO");
				this._GLALAB_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ACC_NO")]
		[DataMember]
		public string ACC_NO
		{
			get { return _ACC_NO; }
			set
			{
				this.OnPropertyValueChange("ACC_NO");
				this._ACC_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MOP_NO")]
		[DataMember]
		public int? MOP_NO
		{
			get { return _MOP_NO; }
			set
			{
				this.OnPropertyValueChange("MOP_NO");
				this._MOP_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CRWVER_ID")]
		[DataMember]
		public string CRWVER_ID
		{
			get { return _CRWVER_ID; }
			set
			{
				this.OnPropertyValueChange("CRWVER_ID");
				this._CRWVER_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CW_FLG")]
		[DataMember]
		public string CW_FLG
		{
			get { return _CW_FLG; }
			set
			{
				this.OnPropertyValueChange("CW_FLG");
				this._CW_FLG = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ORG_NO")]
		[DataMember]
		public int? ORG_NO
		{
			get { return _ORG_NO; }
			set
			{
				this.OnPropertyValueChange("ORG_NO");
				this._ORG_NO = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.CST_NO,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.CST_NO,
				_.CSTVER_ID,
				_.CST_ID,
				_.CST_NAM,
				_.CSTUP_NO,
				_.CSTTRN_FLG,
				_.CST_TYP,
				_.VALID_STA,
				_.CST_DSC,
				_.BEGIN_DTM,
				_.END_DTM,
				_.FSTUSR_ID,
				_.FSTUSR_DTM,
				_.LSTUSR_ID,
				_.LSTUSR_DTM,
				_.MGREMP_NO,
				_.GLACHG_NO,
				_.GLALAB_NO,
				_.ACC_NO,
				_.MOP_NO,
				_.CRWVER_ID,
				_.CW_FLG,
				_.ORG_NO,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._CST_NO,
				this._CSTVER_ID,
				this._CST_ID,
				this._CST_NAM,
				this._CSTUP_NO,
				this._CSTTRN_FLG,
				this._CST_TYP,
				this._VALID_STA,
				this._CST_DSC,
				this._BEGIN_DTM,
				this._END_DTM,
				this._FSTUSR_ID,
				this._FSTUSR_DTM,
				this._LSTUSR_ID,
				this._LSTUSR_DTM,
				this._MGREMP_NO,
				this._GLACHG_NO,
				this._GLALAB_NO,
				this._ACC_NO,
				this._MOP_NO,
				this._CRWVER_ID,
				this._CW_FLG,
				this._ORG_NO,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "OGCSTMST");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CST_NO = new Field("CST_NO", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CSTVER_ID = new Field("CSTVER_ID", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CST_ID = new Field("CST_ID", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CST_NAM = new Field("CST_NAM", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CSTUP_NO = new Field("CSTUP_NO", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CSTTRN_FLG = new Field("CSTTRN_FLG", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CST_TYP = new Field("CST_TYP", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field VALID_STA = new Field("VALID_STA", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CST_DSC = new Field("CST_DSC", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BEGIN_DTM = new Field("BEGIN_DTM", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field END_DTM = new Field("END_DTM", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FSTUSR_ID = new Field("FSTUSR_ID", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FSTUSR_DTM = new Field("FSTUSR_DTM", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LSTUSR_ID = new Field("LSTUSR_ID", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LSTUSR_DTM = new Field("LSTUSR_DTM", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MGREMP_NO = new Field("MGREMP_NO", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GLACHG_NO = new Field("GLACHG_NO", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GLALAB_NO = new Field("GLALAB_NO", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ACC_NO = new Field("ACC_NO", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MOP_NO = new Field("MOP_NO", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CRWVER_ID = new Field("CRWVER_ID", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CW_FLG = new Field("CW_FLG", "OGCSTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ORG_NO = new Field("ORG_NO", "OGCSTMST", "");
		}
		#endregion
	}
}