//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace Power.SPMEMS.Services.Models
{
	/// <summary>
	/// 实体类DCAREAMST。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("DCAREAMST")]
	[Serializable]
	[DataContract]
	public partial class DCAREAMST : Entity
	{
		#region Model
		private int _AREA_NO;
		private int? _ORG_NO;
		private string _VALID_STA;
		private string _AREA_ID;
		private string _AREA_NAM;
		private int? _AREATYP_NO;
		private string _AREA_SHT;
		private string _FSTUSR_ID;
		private DateTime? _FSTUSR_DTM;
		private string _LSTUSR_ID;
		private DateTime? _LSTUSR_DTM;
		private string _CY_FLG;

		/// <summary>
		/// 
		/// </summary>
		[Field("AREA_NO")]
		[DataMember]
		public int AREA_NO
		{
			get { return _AREA_NO; }
			set
			{
				this.OnPropertyValueChange("AREA_NO");
				this._AREA_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ORG_NO")]
		[DataMember]
		public int? ORG_NO
		{
			get { return _ORG_NO; }
			set
			{
				this.OnPropertyValueChange("ORG_NO");
				this._ORG_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("VALID_STA")]
		[DataMember]
		public string VALID_STA
		{
			get { return _VALID_STA; }
			set
			{
				this.OnPropertyValueChange("VALID_STA");
				this._VALID_STA = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AREA_ID")]
		[DataMember]
		public string AREA_ID
		{
			get { return _AREA_ID; }
			set
			{
				this.OnPropertyValueChange("AREA_ID");
				this._AREA_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AREA_NAM")]
		[DataMember]
		public string AREA_NAM
		{
			get { return _AREA_NAM; }
			set
			{
				this.OnPropertyValueChange("AREA_NAM");
				this._AREA_NAM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AREATYP_NO")]
		[DataMember]
		public int? AREATYP_NO
		{
			get { return _AREATYP_NO; }
			set
			{
				this.OnPropertyValueChange("AREATYP_NO");
				this._AREATYP_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AREA_SHT")]
		[DataMember]
		public string AREA_SHT
		{
			get { return _AREA_SHT; }
			set
			{
				this.OnPropertyValueChange("AREA_SHT");
				this._AREA_SHT = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FSTUSR_ID")]
		[DataMember]
		public string FSTUSR_ID
		{
			get { return _FSTUSR_ID; }
			set
			{
				this.OnPropertyValueChange("FSTUSR_ID");
				this._FSTUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FSTUSR_DTM")]
		[DataMember]
		public DateTime? FSTUSR_DTM
		{
			get { return _FSTUSR_DTM; }
			set
			{
				this.OnPropertyValueChange("FSTUSR_DTM");
				this._FSTUSR_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LSTUSR_ID")]
		[DataMember]
		public string LSTUSR_ID
		{
			get { return _LSTUSR_ID; }
			set
			{
				this.OnPropertyValueChange("LSTUSR_ID");
				this._LSTUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LSTUSR_DTM")]
		[DataMember]
		public DateTime? LSTUSR_DTM
		{
			get { return _LSTUSR_DTM; }
			set
			{
				this.OnPropertyValueChange("LSTUSR_DTM");
				this._LSTUSR_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CY_FLG")]
		[DataMember]
		public string CY_FLG
		{
			get { return _CY_FLG; }
			set
			{
				this.OnPropertyValueChange("CY_FLG");
				this._CY_FLG = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.AREA_NO,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.AREA_NO,
				_.ORG_NO,
				_.VALID_STA,
				_.AREA_ID,
				_.AREA_NAM,
				_.AREATYP_NO,
				_.AREA_SHT,
				_.FSTUSR_ID,
				_.FSTUSR_DTM,
				_.LSTUSR_ID,
				_.LSTUSR_DTM,
				_.CY_FLG,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._AREA_NO,
				this._ORG_NO,
				this._VALID_STA,
				this._AREA_ID,
				this._AREA_NAM,
				this._AREATYP_NO,
				this._AREA_SHT,
				this._FSTUSR_ID,
				this._FSTUSR_DTM,
				this._LSTUSR_ID,
				this._LSTUSR_DTM,
				this._CY_FLG,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "DCAREAMST");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AREA_NO = new Field("AREA_NO", "DCAREAMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ORG_NO = new Field("ORG_NO", "DCAREAMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field VALID_STA = new Field("VALID_STA", "DCAREAMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AREA_ID = new Field("AREA_ID", "DCAREAMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AREA_NAM = new Field("AREA_NAM", "DCAREAMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AREATYP_NO = new Field("AREATYP_NO", "DCAREAMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AREA_SHT = new Field("AREA_SHT", "DCAREAMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FSTUSR_ID = new Field("FSTUSR_ID", "DCAREAMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FSTUSR_DTM = new Field("FSTUSR_DTM", "DCAREAMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LSTUSR_ID = new Field("LSTUSR_ID", "DCAREAMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LSTUSR_DTM = new Field("LSTUSR_DTM", "DCAREAMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CY_FLG = new Field("CY_FLG", "DCAREAMST", "");
		}
		#endregion
	}
}