//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace Power.SPMEMS.Services.Models
{
	/// <summary>
	/// 实体类DCWTDURMST。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("DCWTDURMST")]
	[Serializable]
	[DataContract]
	public partial class DCWTDURMST : Entity
	{
		#region Model
		private int _DUR_NO;
		private int? _ORG_NO;
		private string _DUR_STA;
		private string _DUR_ID;
		private string _DUR_NAM;
		private string _YEAR;
		private string _FSTUSR_ID;
		private DateTime? _FSTUSR_DTM;
		private string _LSTUSR_ID;
		private DateTime? _LSTUSR_DTM;
		private string _DUR_NOT;
		private string _VALID_STA;

		/// <summary>
		/// 
		/// </summary>
		[Field("DUR_NO")]
		[DataMember]
		public int DUR_NO
		{
			get { return _DUR_NO; }
			set
			{
				this.OnPropertyValueChange("DUR_NO");
				this._DUR_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ORG_NO")]
		[DataMember]
		public int? ORG_NO
		{
			get { return _ORG_NO; }
			set
			{
				this.OnPropertyValueChange("ORG_NO");
				this._ORG_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DUR_STA")]
		[DataMember]
		public string DUR_STA
		{
			get { return _DUR_STA; }
			set
			{
				this.OnPropertyValueChange("DUR_STA");
				this._DUR_STA = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DUR_ID")]
		[DataMember]
		public string DUR_ID
		{
			get { return _DUR_ID; }
			set
			{
				this.OnPropertyValueChange("DUR_ID");
				this._DUR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DUR_NAM")]
		[DataMember]
		public string DUR_NAM
		{
			get { return _DUR_NAM; }
			set
			{
				this.OnPropertyValueChange("DUR_NAM");
				this._DUR_NAM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("YEAR")]
		[DataMember]
		public string YEAR
		{
			get { return _YEAR; }
			set
			{
				this.OnPropertyValueChange("YEAR");
				this._YEAR = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FSTUSR_ID")]
		[DataMember]
		public string FSTUSR_ID
		{
			get { return _FSTUSR_ID; }
			set
			{
				this.OnPropertyValueChange("FSTUSR_ID");
				this._FSTUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FSTUSR_DTM")]
		[DataMember]
		public DateTime? FSTUSR_DTM
		{
			get { return _FSTUSR_DTM; }
			set
			{
				this.OnPropertyValueChange("FSTUSR_DTM");
				this._FSTUSR_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LSTUSR_ID")]
		[DataMember]
		public string LSTUSR_ID
		{
			get { return _LSTUSR_ID; }
			set
			{
				this.OnPropertyValueChange("LSTUSR_ID");
				this._LSTUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LSTUSR_DTM")]
		[DataMember]
		public DateTime? LSTUSR_DTM
		{
			get { return _LSTUSR_DTM; }
			set
			{
				this.OnPropertyValueChange("LSTUSR_DTM");
				this._LSTUSR_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DUR_NOT")]
		[DataMember]
		public string DUR_NOT
		{
			get { return _DUR_NOT; }
			set
			{
				this.OnPropertyValueChange("DUR_NOT");
				this._DUR_NOT = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("VALID_STA")]
		[DataMember]
		public string VALID_STA
		{
			get { return _VALID_STA; }
			set
			{
				this.OnPropertyValueChange("VALID_STA");
				this._VALID_STA = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.DUR_NO,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.DUR_NO,
				_.ORG_NO,
				_.DUR_STA,
				_.DUR_ID,
				_.DUR_NAM,
				_.YEAR,
				_.FSTUSR_ID,
				_.FSTUSR_DTM,
				_.LSTUSR_ID,
				_.LSTUSR_DTM,
				_.DUR_NOT,
				_.VALID_STA,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._DUR_NO,
				this._ORG_NO,
				this._DUR_STA,
				this._DUR_ID,
				this._DUR_NAM,
				this._YEAR,
				this._FSTUSR_ID,
				this._FSTUSR_DTM,
				this._LSTUSR_ID,
				this._LSTUSR_DTM,
				this._DUR_NOT,
				this._VALID_STA,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "DCWTDURMST");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DUR_NO = new Field("DUR_NO", "DCWTDURMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ORG_NO = new Field("ORG_NO", "DCWTDURMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DUR_STA = new Field("DUR_STA", "DCWTDURMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DUR_ID = new Field("DUR_ID", "DCWTDURMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DUR_NAM = new Field("DUR_NAM", "DCWTDURMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field YEAR = new Field("YEAR", "DCWTDURMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FSTUSR_ID = new Field("FSTUSR_ID", "DCWTDURMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FSTUSR_DTM = new Field("FSTUSR_DTM", "DCWTDURMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LSTUSR_ID = new Field("LSTUSR_ID", "DCWTDURMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LSTUSR_DTM = new Field("LSTUSR_DTM", "DCWTDURMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DUR_NOT = new Field("DUR_NOT", "DCWTDURMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field VALID_STA = new Field("VALID_STA", "DCWTDURMST", "");
		}
		#endregion
	}
}