//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace Power.SPMEMS.Services.Models
{
	/// <summary>
	/// 实体类NPS_DES_ArtificialTime。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("NPS_DES_ArtificialTime")]
	[Serializable]
	[DataContract]
	public partial class NPS_DES_ArtificialTime : Entity
	{
		#region Model
		private Guid _ID;
		private string _Code;
		private string _Title;
		private string _Year;
		private string _Week;
		private string _Rec;
		private string _SKL;
		private string _User;
		private string _Wtlx;
		private string _SumFdwt;
		private string _SumJ;
		private string _SumactWt;
		private string _Kqsj;
		private string _TableName;
		private Guid? _BizAreaId;
		private int? _Sequ;
		private int? _Status;
		private Guid? _RegHumId;
		private string _RegHumName;
		private DateTime? _RegDate;
		private Guid? _RegPosiId;
		private Guid? _RegDeptId;
		private Guid? _EpsProjId;
		private Guid? _RecycleHumId;
		private Guid? _UpdHumId;
		private string _UpdHumName;
		private DateTime? _UpdDate;
		private Guid? _ApprHumId;
		private string _ApprHumName;
		private DateTime? _ApprDate;
		private string _Remark;
		private Guid? _OwnProjId;
		private string _OwnProjName;
		private string _EpsProjCode;
		private string _EpsProjName;
		private Guid? _CompanyID;
		private string _CompanyCode;
		private string _CompanyName;
		private string _FormType;
		private string _NoFinishMemo;
		private string _CompareHumName;
		private string _CompareHumCode;
		private DateTime? _CompareDate;
		private string _SumDesignNo;
		private string _SumVersion;
		private string _SumRequestName;
		private string _SumRequestVersion;
		private string _SPMCode;

		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		[DataMember]
		public Guid ID
		{
			get { return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Code")]
		[DataMember]
		public string Code
		{
			get { return _Code; }
			set
			{
				this.OnPropertyValueChange("Code");
				this._Code = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Title")]
		[DataMember]
		public string Title
		{
			get { return _Title; }
			set
			{
				this.OnPropertyValueChange("Title");
				this._Title = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Year")]
		[DataMember]
		public string Year
		{
			get { return _Year; }
			set
			{
				this.OnPropertyValueChange("Year");
				this._Year = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Week")]
		[DataMember]
		public string Week
		{
			get { return _Week; }
			set
			{
				this.OnPropertyValueChange("Week");
				this._Week = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Rec")]
		[DataMember]
		public string Rec
		{
			get { return _Rec; }
			set
			{
				this.OnPropertyValueChange("Rec");
				this._Rec = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SKL")]
		[DataMember]
		public string SKL
		{
			get { return _SKL; }
			set
			{
				this.OnPropertyValueChange("SKL");
				this._SKL = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("User")]
		[DataMember]
		public string User
		{
			get { return _User; }
			set
			{
				this.OnPropertyValueChange("User");
				this._User = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Wtlx")]
		[DataMember]
		public string Wtlx
		{
			get { return _Wtlx; }
			set
			{
				this.OnPropertyValueChange("Wtlx");
				this._Wtlx = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SumFdwt")]
		[DataMember]
		public string SumFdwt
		{
			get { return _SumFdwt; }
			set
			{
				this.OnPropertyValueChange("SumFdwt");
				this._SumFdwt = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SumJ")]
		[DataMember]
		public string SumJ
		{
			get { return _SumJ; }
			set
			{
				this.OnPropertyValueChange("SumJ");
				this._SumJ = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SumactWt")]
		[DataMember]
		public string SumactWt
		{
			get { return _SumactWt; }
			set
			{
				this.OnPropertyValueChange("SumactWt");
				this._SumactWt = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Kqsj")]
		[DataMember]
		public string Kqsj
		{
			get { return _Kqsj; }
			set
			{
				this.OnPropertyValueChange("Kqsj");
				this._Kqsj = value;
			}
		}
		/// <summary>
		/// 数据所属表名
		/// </summary>
		[Field("TableName")]
		[DataMember]
		public string TableName
		{
			get { return _TableName; }
			set
			{
				this.OnPropertyValueChange("TableName");
				this._TableName = value;
			}
		}
		/// <summary>
		/// 数据录入业务域Id
		/// </summary>
		[Field("BizAreaId")]
		[DataMember]
		public Guid? BizAreaId
		{
			get { return _BizAreaId; }
			set
			{
				this.OnPropertyValueChange("BizAreaId");
				this._BizAreaId = value;
			}
		}
		/// <summary>
		/// 序号
		/// </summary>
		[Field("Sequ")]
		[DataMember]
		public int? Sequ
		{
			get { return _Sequ; }
			set
			{
				this.OnPropertyValueChange("Sequ");
				this._Sequ = value;
			}
		}
		/// <summary>
		/// 表单状态
		/// </summary>
		[Field("Status")]
		[DataMember]
		public int? Status
		{
			get { return _Status; }
			set
			{
				this.OnPropertyValueChange("Status");
				this._Status = value;
			}
		}
		/// <summary>
		/// 录入人Id
		/// </summary>
		[Field("RegHumId")]
		[DataMember]
		public Guid? RegHumId
		{
			get { return _RegHumId; }
			set
			{
				this.OnPropertyValueChange("RegHumId");
				this._RegHumId = value;
			}
		}
		/// <summary>
		/// 录入人名称
		/// </summary>
		[Field("RegHumName")]
		[DataMember]
		public string RegHumName
		{
			get { return _RegHumName; }
			set
			{
				this.OnPropertyValueChange("RegHumName");
				this._RegHumName = value;
			}
		}
		/// <summary>
		/// 录入日期
		/// </summary>
		[Field("RegDate")]
		[DataMember]
		public DateTime? RegDate
		{
			get { return _RegDate; }
			set
			{
				this.OnPropertyValueChange("RegDate");
				this._RegDate = value;
			}
		}
		/// <summary>
		/// 录入人岗位Id
		/// </summary>
		[Field("RegPosiId")]
		[DataMember]
		public Guid? RegPosiId
		{
			get { return _RegPosiId; }
			set
			{
				this.OnPropertyValueChange("RegPosiId");
				this._RegPosiId = value;
			}
		}
		/// <summary>
		/// 录入人部门Id
		/// </summary>
		[Field("RegDeptId")]
		[DataMember]
		public Guid? RegDeptId
		{
			get { return _RegDeptId; }
			set
			{
				this.OnPropertyValueChange("RegDeptId");
				this._RegDeptId = value;
			}
		}
		/// <summary>
		/// 记录所属EPS节点Id
		/// </summary>
		[Field("EpsProjId")]
		[DataMember]
		public Guid? EpsProjId
		{
			get { return _EpsProjId; }
			set
			{
				this.OnPropertyValueChange("EpsProjId");
				this._EpsProjId = value;
			}
		}
		/// <summary>
		/// 删除人Id
		/// </summary>
		[Field("RecycleHumId")]
		[DataMember]
		public Guid? RecycleHumId
		{
			get { return _RecycleHumId; }
			set
			{
				this.OnPropertyValueChange("RecycleHumId");
				this._RecycleHumId = value;
			}
		}
		/// <summary>
		/// 最后更新人Id
		/// </summary>
		[Field("UpdHumId")]
		[DataMember]
		public Guid? UpdHumId
		{
			get { return _UpdHumId; }
			set
			{
				this.OnPropertyValueChange("UpdHumId");
				this._UpdHumId = value;
			}
		}
		/// <summary>
		/// 最后更新人名称
		/// </summary>
		[Field("UpdHumName")]
		[DataMember]
		public string UpdHumName
		{
			get { return _UpdHumName; }
			set
			{
				this.OnPropertyValueChange("UpdHumName");
				this._UpdHumName = value;
			}
		}
		/// <summary>
		/// 最后更新日期
		/// </summary>
		[Field("UpdDate")]
		[DataMember]
		public DateTime? UpdDate
		{
			get { return _UpdDate; }
			set
			{
				this.OnPropertyValueChange("UpdDate");
				this._UpdDate = value;
			}
		}
		/// <summary>
		/// 批准人Id
		/// </summary>
		[Field("ApprHumId")]
		[DataMember]
		public Guid? ApprHumId
		{
			get { return _ApprHumId; }
			set
			{
				this.OnPropertyValueChange("ApprHumId");
				this._ApprHumId = value;
			}
		}
		/// <summary>
		/// 批准人名称
		/// </summary>
		[Field("ApprHumName")]
		[DataMember]
		public string ApprHumName
		{
			get { return _ApprHumName; }
			set
			{
				this.OnPropertyValueChange("ApprHumName");
				this._ApprHumName = value;
			}
		}
		/// <summary>
		/// 批准日期
		/// </summary>
		[Field("ApprDate")]
		[DataMember]
		public DateTime? ApprDate
		{
			get { return _ApprDate; }
			set
			{
				this.OnPropertyValueChange("ApprDate");
				this._ApprDate = value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		[Field("Remark")]
		[DataMember]
		public string Remark
		{
			get { return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 所属项目Id
		/// </summary>
		[Field("OwnProjId")]
		[DataMember]
		public Guid? OwnProjId
		{
			get { return _OwnProjId; }
			set
			{
				this.OnPropertyValueChange("OwnProjId");
				this._OwnProjId = value;
			}
		}
		/// <summary>
		/// 管理层级名称
		/// </summary>
		[Field("OwnProjName")]
		[DataMember]
		public string OwnProjName
		{
			get { return _OwnProjName; }
			set
			{
				this.OnPropertyValueChange("OwnProjName");
				this._OwnProjName = value;
			}
		}
		/// <summary>
		/// EPS编号
		/// </summary>
		[Field("EpsProjCode")]
		[DataMember]
		public string EpsProjCode
		{
			get { return _EpsProjCode; }
			set
			{
				this.OnPropertyValueChange("EpsProjCode");
				this._EpsProjCode = value;
			}
		}
		/// <summary>
		/// EPS名称
		/// </summary>
		[Field("EpsProjName")]
		[DataMember]
		public string EpsProjName
		{
			get { return _EpsProjName; }
			set
			{
				this.OnPropertyValueChange("EpsProjName");
				this._EpsProjName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CompanyID")]
		[DataMember]
		public Guid? CompanyID
		{
			get { return _CompanyID; }
			set
			{
				this.OnPropertyValueChange("CompanyID");
				this._CompanyID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CompanyCode")]
		[DataMember]
		public string CompanyCode
		{
			get { return _CompanyCode; }
			set
			{
				this.OnPropertyValueChange("CompanyCode");
				this._CompanyCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CompanyName")]
		[DataMember]
		public string CompanyName
		{
			get { return _CompanyName; }
			set
			{
				this.OnPropertyValueChange("CompanyName");
				this._CompanyName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FormType")]
		[DataMember]
		public string FormType
		{
			get { return _FormType; }
			set
			{
				this.OnPropertyValueChange("FormType");
				this._FormType = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("NoFinishMemo")]
		[DataMember]
		public string NoFinishMemo
		{
			get { return _NoFinishMemo; }
			set
			{
				this.OnPropertyValueChange("NoFinishMemo");
				this._NoFinishMemo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CompareHumName")]
		[DataMember]
		public string CompareHumName
		{
			get { return _CompareHumName; }
			set
			{
				this.OnPropertyValueChange("CompareHumName");
				this._CompareHumName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CompareHumCode")]
		[DataMember]
		public string CompareHumCode
		{
			get { return _CompareHumCode; }
			set
			{
				this.OnPropertyValueChange("CompareHumCode");
				this._CompareHumCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CompareDate")]
		[DataMember]
		public DateTime? CompareDate
		{
			get { return _CompareDate; }
			set
			{
				this.OnPropertyValueChange("CompareDate");
				this._CompareDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SumDesignNo")]
		[DataMember]
		public string SumDesignNo
		{
			get { return _SumDesignNo; }
			set
			{
				this.OnPropertyValueChange("SumDesignNo");
				this._SumDesignNo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SumVersion")]
		[DataMember]
		public string SumVersion
		{
			get { return _SumVersion; }
			set
			{
				this.OnPropertyValueChange("SumVersion");
				this._SumVersion = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SumRequestName")]
		[DataMember]
		public string SumRequestName
		{
			get { return _SumRequestName; }
			set
			{
				this.OnPropertyValueChange("SumRequestName");
				this._SumRequestName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SumRequestVersion")]
		[DataMember]
		public string SumRequestVersion
		{
			get { return _SumRequestVersion; }
			set
			{
				this.OnPropertyValueChange("SumRequestVersion");
				this._SumRequestVersion = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SPMCode")]
		[DataMember]
		public string SPMCode
		{
			get { return _SPMCode; }
			set
			{
				this.OnPropertyValueChange("SPMCode");
				this._SPMCode = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.Code,
				_.Title,
				_.Year,
				_.Week,
				_.Rec,
				_.SKL,
				_.User,
				_.Wtlx,
				_.SumFdwt,
				_.SumJ,
				_.SumactWt,
				_.Kqsj,
				_.TableName,
				_.BizAreaId,
				_.Sequ,
				_.Status,
				_.RegHumId,
				_.RegHumName,
				_.RegDate,
				_.RegPosiId,
				_.RegDeptId,
				_.EpsProjId,
				_.RecycleHumId,
				_.UpdHumId,
				_.UpdHumName,
				_.UpdDate,
				_.ApprHumId,
				_.ApprHumName,
				_.ApprDate,
				_.Remark,
				_.OwnProjId,
				_.OwnProjName,
				_.EpsProjCode,
				_.EpsProjName,
				_.CompanyID,
				_.CompanyCode,
				_.CompanyName,
				_.FormType,
				_.NoFinishMemo,
				_.CompareHumName,
				_.CompareHumCode,
				_.CompareDate,
				_.SumDesignNo,
				_.SumVersion,
				_.SumRequestName,
				_.SumRequestVersion,
				_.SPMCode,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._Code,
				this._Title,
				this._Year,
				this._Week,
				this._Rec,
				this._SKL,
				this._User,
				this._Wtlx,
				this._SumFdwt,
				this._SumJ,
				this._SumactWt,
				this._Kqsj,
				this._TableName,
				this._BizAreaId,
				this._Sequ,
				this._Status,
				this._RegHumId,
				this._RegHumName,
				this._RegDate,
				this._RegPosiId,
				this._RegDeptId,
				this._EpsProjId,
				this._RecycleHumId,
				this._UpdHumId,
				this._UpdHumName,
				this._UpdDate,
				this._ApprHumId,
				this._ApprHumName,
				this._ApprDate,
				this._Remark,
				this._OwnProjId,
				this._OwnProjName,
				this._EpsProjCode,
				this._EpsProjName,
				this._CompanyID,
				this._CompanyCode,
				this._CompanyName,
				this._FormType,
				this._NoFinishMemo,
				this._CompareHumName,
				this._CompareHumCode,
				this._CompareDate,
				this._SumDesignNo,
				this._SumVersion,
				this._SumRequestName,
				this._SumRequestVersion,
				this._SPMCode,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "NPS_DES_ArtificialTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Code = new Field("Code", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Title = new Field("Title", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Year = new Field("Year", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Week = new Field("Week", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Rec = new Field("Rec", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SKL = new Field("SKL", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field User = new Field("User", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Wtlx = new Field("Wtlx", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SumFdwt = new Field("SumFdwt", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SumJ = new Field("SumJ", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SumactWt = new Field("SumactWt", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Kqsj = new Field("Kqsj", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 数据所属表名
			/// </summary>
			public readonly static Field TableName = new Field("TableName", "NPS_DES_ArtificialTime", "数据所属表名");
			/// <summary>
			/// 数据录入业务域Id
			/// </summary>
			public readonly static Field BizAreaId = new Field("BizAreaId", "NPS_DES_ArtificialTime", "数据录入业务域Id");
			/// <summary>
			/// 序号
			/// </summary>
			public readonly static Field Sequ = new Field("Sequ", "NPS_DES_ArtificialTime", "序号");
			/// <summary>
			/// 表单状态
			/// </summary>
			public readonly static Field Status = new Field("Status", "NPS_DES_ArtificialTime", "表单状态");
			/// <summary>
			/// 录入人Id
			/// </summary>
			public readonly static Field RegHumId = new Field("RegHumId", "NPS_DES_ArtificialTime", "录入人Id");
			/// <summary>
			/// 录入人名称
			/// </summary>
			public readonly static Field RegHumName = new Field("RegHumName", "NPS_DES_ArtificialTime", "录入人名称");
			/// <summary>
			/// 录入日期
			/// </summary>
			public readonly static Field RegDate = new Field("RegDate", "NPS_DES_ArtificialTime", "录入日期");
			/// <summary>
			/// 录入人岗位Id
			/// </summary>
			public readonly static Field RegPosiId = new Field("RegPosiId", "NPS_DES_ArtificialTime", "录入人岗位Id");
			/// <summary>
			/// 录入人部门Id
			/// </summary>
			public readonly static Field RegDeptId = new Field("RegDeptId", "NPS_DES_ArtificialTime", "录入人部门Id");
			/// <summary>
			/// 记录所属EPS节点Id
			/// </summary>
			public readonly static Field EpsProjId = new Field("EpsProjId", "NPS_DES_ArtificialTime", "记录所属EPS节点Id");
			/// <summary>
			/// 删除人Id
			/// </summary>
			public readonly static Field RecycleHumId = new Field("RecycleHumId", "NPS_DES_ArtificialTime", "删除人Id");
			/// <summary>
			/// 最后更新人Id
			/// </summary>
			public readonly static Field UpdHumId = new Field("UpdHumId", "NPS_DES_ArtificialTime", "最后更新人Id");
			/// <summary>
			/// 最后更新人名称
			/// </summary>
			public readonly static Field UpdHumName = new Field("UpdHumName", "NPS_DES_ArtificialTime", "最后更新人名称");
			/// <summary>
			/// 最后更新日期
			/// </summary>
			public readonly static Field UpdDate = new Field("UpdDate", "NPS_DES_ArtificialTime", "最后更新日期");
			/// <summary>
			/// 批准人Id
			/// </summary>
			public readonly static Field ApprHumId = new Field("ApprHumId", "NPS_DES_ArtificialTime", "批准人Id");
			/// <summary>
			/// 批准人名称
			/// </summary>
			public readonly static Field ApprHumName = new Field("ApprHumName", "NPS_DES_ArtificialTime", "批准人名称");
			/// <summary>
			/// 批准日期
			/// </summary>
			public readonly static Field ApprDate = new Field("ApprDate", "NPS_DES_ArtificialTime", "批准日期");
			/// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "NPS_DES_ArtificialTime", "备注");
			/// <summary>
			/// 所属项目Id
			/// </summary>
			public readonly static Field OwnProjId = new Field("OwnProjId", "NPS_DES_ArtificialTime", "所属项目Id");
			/// <summary>
			/// 管理层级名称
			/// </summary>
			public readonly static Field OwnProjName = new Field("OwnProjName", "NPS_DES_ArtificialTime", "管理层级名称");
			/// <summary>
			/// EPS编号
			/// </summary>
			public readonly static Field EpsProjCode = new Field("EpsProjCode", "NPS_DES_ArtificialTime", "EPS编号");
			/// <summary>
			/// EPS名称
			/// </summary>
			public readonly static Field EpsProjName = new Field("EpsProjName", "NPS_DES_ArtificialTime", "EPS名称");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CompanyID = new Field("CompanyID", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CompanyCode = new Field("CompanyCode", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CompanyName = new Field("CompanyName", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FormType = new Field("FormType", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field NoFinishMemo = new Field("NoFinishMemo", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CompareHumName = new Field("CompareHumName", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CompareHumCode = new Field("CompareHumCode", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CompareDate = new Field("CompareDate", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SumDesignNo = new Field("SumDesignNo", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SumVersion = new Field("SumVersion", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SumRequestName = new Field("SumRequestName", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SumRequestVersion = new Field("SumRequestVersion", "NPS_DES_ArtificialTime", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SPMCode = new Field("SPMCode", "NPS_DES_ArtificialTime", "");
		}
		#endregion
	}
}