//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Power.SPMEMS.Services
{
	/// <summary>
	/// 实体类NPS_BID_StatusTable。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("NPS_BID_StatusTable")]
	[Serializable]
	public partial class NPS_BID_StatusTable : Entity
	{
		#region Model
		private Guid _ID;
		private string _Code;
		private string _Title;
		private string _ProjectDep;
		private string _AdditionalQua;
		private string _RequestCode;
		private string _RequestVersion;
		private string _RequestAmount;
		private DateTime? _RequestDate;
		private DateTime? _MaterialDate;
		private string _ConAmount;
		private DateTime? _ConSignDate;
		private string _ReleaseAmount;
		private DateTime? _ReleaseDate;
		private string _ActualDate;
		private string _InventoryAmount;
		private string _TableName;
		private Guid? _BizAreaId;
		private int? _Sequ;
		private int? _Status;
		private Guid? _RegHumId;
		private string _RegHumName;
		private DateTime? _RegDate;
		private Guid? _RegPosiId;
		private Guid? _RegDeptId;
		private Guid? _EpsProjId;
		private Guid? _RecycleHumId;
		private Guid? _UpdHumId;
		private string _UpdHumName;
		private DateTime? _UpdDate;
		private Guid? _ApprHumId;
		private string _ApprHumName;
		private DateTime? _ApprDate;
		private string _Remark;
		private Guid? _OwnProjId;
		private string _OwnProjName;
		private string _EpsProjCode;
		private string _EpsProjName;
		private Guid? _CompanyID;
		private string _CompanyCode;
		private string _CompanyName;
		private string _SPMCode;
		private string _SPMDes;

		/// <summary>
		/// 主键
		/// </summary>
		[Field("ID")]
		public Guid ID
		{
			get { return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 编号
		/// </summary>
		[Field("Code")]
		public string Code
		{
			get { return _Code; }
			set
			{
				this.OnPropertyValueChange("Code");
				this._Code = value;
			}
		}
		/// <summary>
		/// 标题
		/// </summary>
		[Field("Title")]
		public string Title
		{
			get { return _Title; }
			set
			{
				this.OnPropertyValueChange("Title");
				this._Title = value;
			}
		}
		/// <summary>
		/// 所属项目部
		/// </summary>
		[Field("ProjectDep")]
		public string ProjectDep
		{
			get { return _ProjectDep; }
			set
			{
				this.OnPropertyValueChange("ProjectDep");
				this._ProjectDep = value;
			}
		}
		/// <summary>
		/// 主项
		/// </summary>
		[Field("AdditionalQua")]
		public string AdditionalQua
		{
			get { return _AdditionalQua; }
			set
			{
				this.OnPropertyValueChange("AdditionalQua");
				this._AdditionalQua = value;
			}
		}
		/// <summary>
		/// 请购单号
		/// </summary>
		[Field("RequestCode")]
		public string RequestCode
		{
			get { return _RequestCode; }
			set
			{
				this.OnPropertyValueChange("RequestCode");
				this._RequestCode = value;
			}
		}
		/// <summary>
		/// 请购文件版本
		/// </summary>
		[Field("RequestVersion")]
		public string RequestVersion
		{
			get { return _RequestVersion; }
			set
			{
				this.OnPropertyValueChange("RequestVersion");
				this._RequestVersion = value;
			}
		}
		/// <summary>
		/// 请购数量
		/// </summary>
		[Field("RequestAmount")]
		public string RequestAmount
		{
			get { return _RequestAmount; }
			set
			{
				this.OnPropertyValueChange("RequestAmount");
				this._RequestAmount = value;
			}
		}
		/// <summary>
		/// 请购单发布时间
		/// </summary>
		[Field("RequestDate")]
		public DateTime? RequestDate
		{
			get { return _RequestDate; }
			set
			{
				this.OnPropertyValueChange("RequestDate");
				this._RequestDate = value;
			}
		}
		/// <summary>
		/// 材料要求到货时间
		/// </summary>
		[Field("MaterialDate")]
		public DateTime? MaterialDate
		{
			get { return _MaterialDate; }
			set
			{
				this.OnPropertyValueChange("MaterialDate");
				this._MaterialDate = value;
			}
		}
		/// <summary>
		/// 合同总量
		/// </summary>
		[Field("ConAmount")]
		public string ConAmount
		{
			get { return _ConAmount; }
			set
			{
				this.OnPropertyValueChange("ConAmount");
				this._ConAmount = value;
			}
		}
		/// <summary>
		/// 合同签订时间
		/// </summary>
		[Field("ConSignDate")]
		public DateTime? ConSignDate
		{
			get { return _ConSignDate; }
			set
			{
				this.OnPropertyValueChange("ConSignDate");
				this._ConSignDate = value;
			}
		}
		/// <summary>
		/// 放行数量
		/// </summary>
		[Field("ReleaseAmount")]
		public string ReleaseAmount
		{
			get { return _ReleaseAmount; }
			set
			{
				this.OnPropertyValueChange("ReleaseAmount");
				this._ReleaseAmount = value;
			}
		}
		/// <summary>
		/// 放行时间
		/// </summary>
		[Field("ReleaseDate")]
		public DateTime? ReleaseDate
		{
			get { return _ReleaseDate; }
			set
			{
				this.OnPropertyValueChange("ReleaseDate");
				this._ReleaseDate = value;
			}
		}
		/// <summary>
		/// 实际到货时间
		/// </summary>
		[Field("ActualDate")]
		public string ActualDate
		{
			get { return _ActualDate; }
			set
			{
				this.OnPropertyValueChange("ActualDate");
				this._ActualDate = value;
			}
		}
		/// <summary>
		/// 入库总量
		/// </summary>
		[Field("InventoryAmount")]
		public string InventoryAmount
		{
			get { return _InventoryAmount; }
			set
			{
				this.OnPropertyValueChange("InventoryAmount");
				this._InventoryAmount = value;
			}
		}
		/// <summary>
		/// 数据所属表名
		/// </summary>
		[Field("TableName")]
		public string TableName
		{
			get { return _TableName; }
			set
			{
				this.OnPropertyValueChange("TableName");
				this._TableName = value;
			}
		}
		/// <summary>
		/// 数据录入业务域Id
		/// </summary>
		[Field("BizAreaId")]
		public Guid? BizAreaId
		{
			get { return _BizAreaId; }
			set
			{
				this.OnPropertyValueChange("BizAreaId");
				this._BizAreaId = value;
			}
		}
		/// <summary>
		/// 序号
		/// </summary>
		[Field("Sequ")]
		public int? Sequ
		{
			get { return _Sequ; }
			set
			{
				this.OnPropertyValueChange("Sequ");
				this._Sequ = value;
			}
		}
		/// <summary>
		/// 表单状态
		/// </summary>
		[Field("Status")]
		public int? Status
		{
			get { return _Status; }
			set
			{
				this.OnPropertyValueChange("Status");
				this._Status = value;
			}
		}
		/// <summary>
		/// 录入人Id
		/// </summary>
		[Field("RegHumId")]
		public Guid? RegHumId
		{
			get { return _RegHumId; }
			set
			{
				this.OnPropertyValueChange("RegHumId");
				this._RegHumId = value;
			}
		}
		/// <summary>
		/// 录入人名称
		/// </summary>
		[Field("RegHumName")]
		public string RegHumName
		{
			get { return _RegHumName; }
			set
			{
				this.OnPropertyValueChange("RegHumName");
				this._RegHumName = value;
			}
		}
		/// <summary>
		/// 录入日期
		/// </summary>
		[Field("RegDate")]
		public DateTime? RegDate
		{
			get { return _RegDate; }
			set
			{
				this.OnPropertyValueChange("RegDate");
				this._RegDate = value;
			}
		}
		/// <summary>
		/// 录入人岗位Id
		/// </summary>
		[Field("RegPosiId")]
		public Guid? RegPosiId
		{
			get { return _RegPosiId; }
			set
			{
				this.OnPropertyValueChange("RegPosiId");
				this._RegPosiId = value;
			}
		}
		/// <summary>
		/// 录入人部门Id
		/// </summary>
		[Field("RegDeptId")]
		public Guid? RegDeptId
		{
			get { return _RegDeptId; }
			set
			{
				this.OnPropertyValueChange("RegDeptId");
				this._RegDeptId = value;
			}
		}
		/// <summary>
		/// 记录所属EPS节点Id
		/// </summary>
		[Field("EpsProjId")]
		public Guid? EpsProjId
		{
			get { return _EpsProjId; }
			set
			{
				this.OnPropertyValueChange("EpsProjId");
				this._EpsProjId = value;
			}
		}
		/// <summary>
		/// 删除人Id
		/// </summary>
		[Field("RecycleHumId")]
		public Guid? RecycleHumId
		{
			get { return _RecycleHumId; }
			set
			{
				this.OnPropertyValueChange("RecycleHumId");
				this._RecycleHumId = value;
			}
		}
		/// <summary>
		/// 最后更新人Id
		/// </summary>
		[Field("UpdHumId")]
		public Guid? UpdHumId
		{
			get { return _UpdHumId; }
			set
			{
				this.OnPropertyValueChange("UpdHumId");
				this._UpdHumId = value;
			}
		}
		/// <summary>
		/// 最后更新人名称
		/// </summary>
		[Field("UpdHumName")]
		public string UpdHumName
		{
			get { return _UpdHumName; }
			set
			{
				this.OnPropertyValueChange("UpdHumName");
				this._UpdHumName = value;
			}
		}
		/// <summary>
		/// 最后更新日期
		/// </summary>
		[Field("UpdDate")]
		public DateTime? UpdDate
		{
			get { return _UpdDate; }
			set
			{
				this.OnPropertyValueChange("UpdDate");
				this._UpdDate = value;
			}
		}
		/// <summary>
		/// 批准人Id
		/// </summary>
		[Field("ApprHumId")]
		public Guid? ApprHumId
		{
			get { return _ApprHumId; }
			set
			{
				this.OnPropertyValueChange("ApprHumId");
				this._ApprHumId = value;
			}
		}
		/// <summary>
		/// 批准人名称
		/// </summary>
		[Field("ApprHumName")]
		public string ApprHumName
		{
			get { return _ApprHumName; }
			set
			{
				this.OnPropertyValueChange("ApprHumName");
				this._ApprHumName = value;
			}
		}
		/// <summary>
		/// 批准日期
		/// </summary>
		[Field("ApprDate")]
		public DateTime? ApprDate
		{
			get { return _ApprDate; }
			set
			{
				this.OnPropertyValueChange("ApprDate");
				this._ApprDate = value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get { return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 所属项目Id
		/// </summary>
		[Field("OwnProjId")]
		public Guid? OwnProjId
		{
			get { return _OwnProjId; }
			set
			{
				this.OnPropertyValueChange("OwnProjId");
				this._OwnProjId = value;
			}
		}
		/// <summary>
		/// 管理层级名称
		/// </summary>
		[Field("OwnProjName")]
		public string OwnProjName
		{
			get { return _OwnProjName; }
			set
			{
				this.OnPropertyValueChange("OwnProjName");
				this._OwnProjName = value;
			}
		}
		/// <summary>
		/// EPS编号
		/// </summary>
		[Field("EpsProjCode")]
		public string EpsProjCode
		{
			get { return _EpsProjCode; }
			set
			{
				this.OnPropertyValueChange("EpsProjCode");
				this._EpsProjCode = value;
			}
		}
		/// <summary>
		/// EPS名称
		/// </summary>
		[Field("EpsProjName")]
		public string EpsProjName
		{
			get { return _EpsProjName; }
			set
			{
				this.OnPropertyValueChange("EpsProjName");
				this._EpsProjName = value;
			}
		}
		/// <summary>
		/// 单位ID
		/// </summary>
		[Field("CompanyID")]
		public Guid? CompanyID
		{
			get { return _CompanyID; }
			set
			{
				this.OnPropertyValueChange("CompanyID");
				this._CompanyID = value;
			}
		}
		/// <summary>
		/// 单位编号
		/// </summary>
		[Field("CompanyCode")]
		public string CompanyCode
		{
			get { return _CompanyCode; }
			set
			{
				this.OnPropertyValueChange("CompanyCode");
				this._CompanyCode = value;
			}
		}
		/// <summary>
		/// 单位名称
		/// </summary>
		[Field("CompanyName")]
		public string CompanyName
		{
			get { return _CompanyName; }
			set
			{
				this.OnPropertyValueChange("CompanyName");
				this._CompanyName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SPMCode")]
		public string SPMCode
		{
			get { return _SPMCode; }
			set
			{
				this.OnPropertyValueChange("SPMCode");
				this._SPMCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SPMDes")]
		public string SPMDes
		{
			get { return _SPMDes; }
			set
			{
				this.OnPropertyValueChange("SPMDes");
				this._SPMDes = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.Code,
				_.Title,
				_.ProjectDep,
				_.AdditionalQua,
				_.RequestCode,
				_.RequestVersion,
				_.RequestAmount,
				_.RequestDate,
				_.MaterialDate,
				_.ConAmount,
				_.ConSignDate,
				_.ReleaseAmount,
				_.ReleaseDate,
				_.ActualDate,
				_.InventoryAmount,
				_.TableName,
				_.BizAreaId,
				_.Sequ,
				_.Status,
				_.RegHumId,
				_.RegHumName,
				_.RegDate,
				_.RegPosiId,
				_.RegDeptId,
				_.EpsProjId,
				_.RecycleHumId,
				_.UpdHumId,
				_.UpdHumName,
				_.UpdDate,
				_.ApprHumId,
				_.ApprHumName,
				_.ApprDate,
				_.Remark,
				_.OwnProjId,
				_.OwnProjName,
				_.EpsProjCode,
				_.EpsProjName,
				_.CompanyID,
				_.CompanyCode,
				_.CompanyName,
				_.SPMCode,
				_.SPMDes,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._Code,
				this._Title,
				this._ProjectDep,
				this._AdditionalQua,
				this._RequestCode,
				this._RequestVersion,
				this._RequestAmount,
				this._RequestDate,
				this._MaterialDate,
				this._ConAmount,
				this._ConSignDate,
				this._ReleaseAmount,
				this._ReleaseDate,
				this._ActualDate,
				this._InventoryAmount,
				this._TableName,
				this._BizAreaId,
				this._Sequ,
				this._Status,
				this._RegHumId,
				this._RegHumName,
				this._RegDate,
				this._RegPosiId,
				this._RegDeptId,
				this._EpsProjId,
				this._RecycleHumId,
				this._UpdHumId,
				this._UpdHumName,
				this._UpdDate,
				this._ApprHumId,
				this._ApprHumName,
				this._ApprDate,
				this._Remark,
				this._OwnProjId,
				this._OwnProjName,
				this._EpsProjCode,
				this._EpsProjName,
				this._CompanyID,
				this._CompanyCode,
				this._CompanyName,
				this._SPMCode,
				this._SPMDes,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "NPS_BID_StatusTable");
			/// <summary>
			/// 主键
			/// </summary>
			public readonly static Field ID = new Field("ID", "NPS_BID_StatusTable", "主键");
			/// <summary>
			/// 编号
			/// </summary>
			public readonly static Field Code = new Field("Code", "NPS_BID_StatusTable", "编号");
			/// <summary>
			/// 标题
			/// </summary>
			public readonly static Field Title = new Field("Title", "NPS_BID_StatusTable", "标题");
			/// <summary>
			/// 所属项目部
			/// </summary>
			public readonly static Field ProjectDep = new Field("ProjectDep", "NPS_BID_StatusTable", "所属项目部");
			/// <summary>
			/// 主项
			/// </summary>
			public readonly static Field AdditionalQua = new Field("AdditionalQua", "NPS_BID_StatusTable", "主项");
			/// <summary>
			/// 请购单号
			/// </summary>
			public readonly static Field RequestCode = new Field("RequestCode", "NPS_BID_StatusTable", "请购单号");
			/// <summary>
			/// 请购文件版本
			/// </summary>
			public readonly static Field RequestVersion = new Field("RequestVersion", "NPS_BID_StatusTable", "请购文件版本");
			/// <summary>
			/// 请购数量
			/// </summary>
			public readonly static Field RequestAmount = new Field("RequestAmount", "NPS_BID_StatusTable", "请购数量");
			/// <summary>
			/// 请购单发布时间
			/// </summary>
			public readonly static Field RequestDate = new Field("RequestDate", "NPS_BID_StatusTable", "请购单发布时间");
			/// <summary>
			/// 材料要求到货时间
			/// </summary>
			public readonly static Field MaterialDate = new Field("MaterialDate", "NPS_BID_StatusTable", "材料要求到货时间");
			/// <summary>
			/// 合同总量
			/// </summary>
			public readonly static Field ConAmount = new Field("ConAmount", "NPS_BID_StatusTable", "合同总量");
			/// <summary>
			/// 合同签订时间
			/// </summary>
			public readonly static Field ConSignDate = new Field("ConSignDate", "NPS_BID_StatusTable", "合同签订时间");
			/// <summary>
			/// 放行数量
			/// </summary>
			public readonly static Field ReleaseAmount = new Field("ReleaseAmount", "NPS_BID_StatusTable", "放行数量");
			/// <summary>
			/// 放行时间
			/// </summary>
			public readonly static Field ReleaseDate = new Field("ReleaseDate", "NPS_BID_StatusTable", "放行时间");
			/// <summary>
			/// 实际到货时间
			/// </summary>
			public readonly static Field ActualDate = new Field("ActualDate", "NPS_BID_StatusTable", "实际到货时间");
			/// <summary>
			/// 入库总量
			/// </summary>
			public readonly static Field InventoryAmount = new Field("InventoryAmount", "NPS_BID_StatusTable", "入库总量");
			/// <summary>
			/// 数据所属表名
			/// </summary>
			public readonly static Field TableName = new Field("TableName", "NPS_BID_StatusTable", "数据所属表名");
			/// <summary>
			/// 数据录入业务域Id
			/// </summary>
			public readonly static Field BizAreaId = new Field("BizAreaId", "NPS_BID_StatusTable", "数据录入业务域Id");
			/// <summary>
			/// 序号
			/// </summary>
			public readonly static Field Sequ = new Field("Sequ", "NPS_BID_StatusTable", "序号");
			/// <summary>
			/// 表单状态
			/// </summary>
			public readonly static Field Status = new Field("Status", "NPS_BID_StatusTable", "表单状态");
			/// <summary>
			/// 录入人Id
			/// </summary>
			public readonly static Field RegHumId = new Field("RegHumId", "NPS_BID_StatusTable", "录入人Id");
			/// <summary>
			/// 录入人名称
			/// </summary>
			public readonly static Field RegHumName = new Field("RegHumName", "NPS_BID_StatusTable", "录入人名称");
			/// <summary>
			/// 录入日期
			/// </summary>
			public readonly static Field RegDate = new Field("RegDate", "NPS_BID_StatusTable", "录入日期");
			/// <summary>
			/// 录入人岗位Id
			/// </summary>
			public readonly static Field RegPosiId = new Field("RegPosiId", "NPS_BID_StatusTable", "录入人岗位Id");
			/// <summary>
			/// 录入人部门Id
			/// </summary>
			public readonly static Field RegDeptId = new Field("RegDeptId", "NPS_BID_StatusTable", "录入人部门Id");
			/// <summary>
			/// 记录所属EPS节点Id
			/// </summary>
			public readonly static Field EpsProjId = new Field("EpsProjId", "NPS_BID_StatusTable", "记录所属EPS节点Id");
			/// <summary>
			/// 删除人Id
			/// </summary>
			public readonly static Field RecycleHumId = new Field("RecycleHumId", "NPS_BID_StatusTable", "删除人Id");
			/// <summary>
			/// 最后更新人Id
			/// </summary>
			public readonly static Field UpdHumId = new Field("UpdHumId", "NPS_BID_StatusTable", "最后更新人Id");
			/// <summary>
			/// 最后更新人名称
			/// </summary>
			public readonly static Field UpdHumName = new Field("UpdHumName", "NPS_BID_StatusTable", "最后更新人名称");
			/// <summary>
			/// 最后更新日期
			/// </summary>
			public readonly static Field UpdDate = new Field("UpdDate", "NPS_BID_StatusTable", "最后更新日期");
			/// <summary>
			/// 批准人Id
			/// </summary>
			public readonly static Field ApprHumId = new Field("ApprHumId", "NPS_BID_StatusTable", "批准人Id");
			/// <summary>
			/// 批准人名称
			/// </summary>
			public readonly static Field ApprHumName = new Field("ApprHumName", "NPS_BID_StatusTable", "批准人名称");
			/// <summary>
			/// 批准日期
			/// </summary>
			public readonly static Field ApprDate = new Field("ApprDate", "NPS_BID_StatusTable", "批准日期");
			/// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "NPS_BID_StatusTable", "备注");
			/// <summary>
			/// 所属项目Id
			/// </summary>
			public readonly static Field OwnProjId = new Field("OwnProjId", "NPS_BID_StatusTable", "所属项目Id");
			/// <summary>
			/// 管理层级名称
			/// </summary>
			public readonly static Field OwnProjName = new Field("OwnProjName", "NPS_BID_StatusTable", "管理层级名称");
			/// <summary>
			/// EPS编号
			/// </summary>
			public readonly static Field EpsProjCode = new Field("EpsProjCode", "NPS_BID_StatusTable", "EPS编号");
			/// <summary>
			/// EPS名称
			/// </summary>
			public readonly static Field EpsProjName = new Field("EpsProjName", "NPS_BID_StatusTable", "EPS名称");
			/// <summary>
			/// 单位ID
			/// </summary>
			public readonly static Field CompanyID = new Field("CompanyID", "NPS_BID_StatusTable", "单位ID");
			/// <summary>
			/// 单位编号
			/// </summary>
			public readonly static Field CompanyCode = new Field("CompanyCode", "NPS_BID_StatusTable", "单位编号");
			/// <summary>
			/// 单位名称
			/// </summary>
			public readonly static Field CompanyName = new Field("CompanyName", "NPS_BID_StatusTable", "单位名称");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SPMCode = new Field("SPMCode", "NPS_BID_StatusTable", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SPMDes = new Field("SPMDes", "NPS_BID_StatusTable", "");
		}
		#endregion
	}
}