//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Power.SPMEMS.Services
{
	/// <summary>
	/// 实体类PLN_project。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("PLN_project")]
	[Serializable]
	public partial class PLN_project : Entity
	{
		#region Model
		private int _project_id;
		private string _project_guid;
		private string _project_shortname;
		private string _project_name;
		private int? _parent_id;
		private string _parent_guid;
		private string _remark;
		private int? _user_sid;
		private string _user_guid;
		private int? _project_type;
		private decimal? _est_wt;
		private int? _obs_sid;
		private string _obs_guid;
		private int? _haschild;
		private int? _p3ec;
		private int? _treelevel;
		private string _note;
		private int? _p3ec_project_id;
		private int? _contract_id;
		private int? _displayid;
		private int? _discolor;
		private int? _project_type_sid;
		private int? _project_status_sid;
		private string _project_address;
		private DateTime? _target_start_date;
		private DateTime? _target_end_date;
		private DateTime? _act_start_date;
		private DateTime? _act_end_date;
		private DateTime? _data_date;
		private DateTime? _compute_end_date;
		private DateTime? _expect_start_date;
		private DateTime? _expect_end_date;
		private int? _unContract_id;
		private decimal? _complete_pct;
		private bool? _allow_diy_web;
		private int? _program_id;
		private int? _risk_level;
		private string _proj_url;
		private string _def_duration_type;
		private string _def_complete_pct_type;
		private string _def_task_type;
		private int? _acct_id;
		private string _acct_guid;
		private int? _clndr_id;
		private string _clndr_guid;
		private int? _week_id;
		private DateTime? _update_date;
		private decimal? _critical_drtn_hr_cnt;
		private string _critical_path_type;
		private DateTime? _start_date;
		private DateTime? _end_date;
		private int? _Pro_owners;
		private int? _Pro_manager;
		private DateTime? _Pro_time;
		private string _Pro_general_situation;
		private string _Pro_Construction_content;
		private decimal? _Pro_total;
		private int? _STATE;
		private string _zuzhijigou;
		private int? _isLiXiang;
		private int? _adder_sid;
		private DateTime? _add_date;
		private bool? _if_plan;
		private string _LongCode;
		private Guid? _BizAreaId;
		private Guid? _Pro_manager_guid;
		private string _Pro_manager_name;
		private Guid? _Pro_owners_guid;
		private string _Pro_owners_name;
		private string _EpsProjId;
		private string _EpsProjName;
		private int? _EpsProjType;
		private int? _UseOwnProjRight;
		private decimal? _est_wt_value;
		private decimal? _Longitude;
		private decimal? _Latitude;
		private Guid? _RegHumId;
		private string _RegHumName;
		private DateTime? _RegDate;
		private string _update_user;
		private DateTime? _create_date;
		private string _create_user;
		private int? _delete_session_id;
		private DateTime? _delete_date;
		private string _Country;
		private string _Province;
		private string _City;
		private string _County;
		private string _EpsProjIcon;

		/// <summary>
		/// 
		/// </summary>
		[Field("project_id")]
		public int project_id
		{
			get { return _project_id; }
			set
			{
				this.OnPropertyValueChange("project_id");
				this._project_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("project_guid")]
		public string project_guid
		{
			get { return _project_guid; }
			set
			{
				this.OnPropertyValueChange("project_guid");
				this._project_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("project_shortname")]
		public string project_shortname
		{
			get { return _project_shortname; }
			set
			{
				this.OnPropertyValueChange("project_shortname");
				this._project_shortname = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("project_name")]
		public string project_name
		{
			get { return _project_name; }
			set
			{
				this.OnPropertyValueChange("project_name");
				this._project_name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("parent_id")]
		public int? parent_id
		{
			get { return _parent_id; }
			set
			{
				this.OnPropertyValueChange("parent_id");
				this._parent_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("parent_guid")]
		public string parent_guid
		{
			get { return _parent_guid; }
			set
			{
				this.OnPropertyValueChange("parent_guid");
				this._parent_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("remark")]
		public string remark
		{
			get { return _remark; }
			set
			{
				this.OnPropertyValueChange("remark");
				this._remark = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("user_sid")]
		public int? user_sid
		{
			get { return _user_sid; }
			set
			{
				this.OnPropertyValueChange("user_sid");
				this._user_sid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("user_guid")]
		public string user_guid
		{
			get { return _user_guid; }
			set
			{
				this.OnPropertyValueChange("user_guid");
				this._user_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("project_type")]
		public int? project_type
		{
			get { return _project_type; }
			set
			{
				this.OnPropertyValueChange("project_type");
				this._project_type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("est_wt")]
		public decimal? est_wt
		{
			get { return _est_wt; }
			set
			{
				this.OnPropertyValueChange("est_wt");
				this._est_wt = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("obs_sid")]
		public int? obs_sid
		{
			get { return _obs_sid; }
			set
			{
				this.OnPropertyValueChange("obs_sid");
				this._obs_sid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("obs_guid")]
		public string obs_guid
		{
			get { return _obs_guid; }
			set
			{
				this.OnPropertyValueChange("obs_guid");
				this._obs_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("haschild")]
		public int? haschild
		{
			get { return _haschild; }
			set
			{
				this.OnPropertyValueChange("haschild");
				this._haschild = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("p3ec")]
		public int? p3ec
		{
			get { return _p3ec; }
			set
			{
				this.OnPropertyValueChange("p3ec");
				this._p3ec = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("treelevel")]
		public int? treelevel
		{
			get { return _treelevel; }
			set
			{
				this.OnPropertyValueChange("treelevel");
				this._treelevel = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("note")]
		public string note
		{
			get { return _note; }
			set
			{
				this.OnPropertyValueChange("note");
				this._note = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("p3ec_project_id")]
		public int? p3ec_project_id
		{
			get { return _p3ec_project_id; }
			set
			{
				this.OnPropertyValueChange("p3ec_project_id");
				this._p3ec_project_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("contract_id")]
		public int? contract_id
		{
			get { return _contract_id; }
			set
			{
				this.OnPropertyValueChange("contract_id");
				this._contract_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("displayid")]
		public int? displayid
		{
			get { return _displayid; }
			set
			{
				this.OnPropertyValueChange("displayid");
				this._displayid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("discolor")]
		public int? discolor
		{
			get { return _discolor; }
			set
			{
				this.OnPropertyValueChange("discolor");
				this._discolor = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("project_type_sid")]
		public int? project_type_sid
		{
			get { return _project_type_sid; }
			set
			{
				this.OnPropertyValueChange("project_type_sid");
				this._project_type_sid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("project_status_sid")]
		public int? project_status_sid
		{
			get { return _project_status_sid; }
			set
			{
				this.OnPropertyValueChange("project_status_sid");
				this._project_status_sid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("project_address")]
		public string project_address
		{
			get { return _project_address; }
			set
			{
				this.OnPropertyValueChange("project_address");
				this._project_address = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("target_start_date")]
		public DateTime? target_start_date
		{
			get { return _target_start_date; }
			set
			{
				this.OnPropertyValueChange("target_start_date");
				this._target_start_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("target_end_date")]
		public DateTime? target_end_date
		{
			get { return _target_end_date; }
			set
			{
				this.OnPropertyValueChange("target_end_date");
				this._target_end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("act_start_date")]
		public DateTime? act_start_date
		{
			get { return _act_start_date; }
			set
			{
				this.OnPropertyValueChange("act_start_date");
				this._act_start_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("act_end_date")]
		public DateTime? act_end_date
		{
			get { return _act_end_date; }
			set
			{
				this.OnPropertyValueChange("act_end_date");
				this._act_end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("data_date")]
		public DateTime? data_date
		{
			get { return _data_date; }
			set
			{
				this.OnPropertyValueChange("data_date");
				this._data_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("compute_end_date")]
		public DateTime? compute_end_date
		{
			get { return _compute_end_date; }
			set
			{
				this.OnPropertyValueChange("compute_end_date");
				this._compute_end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("expect_start_date")]
		public DateTime? expect_start_date
		{
			get { return _expect_start_date; }
			set
			{
				this.OnPropertyValueChange("expect_start_date");
				this._expect_start_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("expect_end_date")]
		public DateTime? expect_end_date
		{
			get { return _expect_end_date; }
			set
			{
				this.OnPropertyValueChange("expect_end_date");
				this._expect_end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("unContract_id")]
		public int? unContract_id
		{
			get { return _unContract_id; }
			set
			{
				this.OnPropertyValueChange("unContract_id");
				this._unContract_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("complete_pct")]
		public decimal? complete_pct
		{
			get { return _complete_pct; }
			set
			{
				this.OnPropertyValueChange("complete_pct");
				this._complete_pct = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("allow_diy_web")]
		public bool? allow_diy_web
		{
			get { return _allow_diy_web; }
			set
			{
				this.OnPropertyValueChange("allow_diy_web");
				this._allow_diy_web = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("program_id")]
		public int? program_id
		{
			get { return _program_id; }
			set
			{
				this.OnPropertyValueChange("program_id");
				this._program_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("risk_level")]
		public int? risk_level
		{
			get { return _risk_level; }
			set
			{
				this.OnPropertyValueChange("risk_level");
				this._risk_level = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("proj_url")]
		public string proj_url
		{
			get { return _proj_url; }
			set
			{
				this.OnPropertyValueChange("proj_url");
				this._proj_url = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("def_duration_type")]
		public string def_duration_type
		{
			get { return _def_duration_type; }
			set
			{
				this.OnPropertyValueChange("def_duration_type");
				this._def_duration_type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("def_complete_pct_type")]
		public string def_complete_pct_type
		{
			get { return _def_complete_pct_type; }
			set
			{
				this.OnPropertyValueChange("def_complete_pct_type");
				this._def_complete_pct_type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("def_task_type")]
		public string def_task_type
		{
			get { return _def_task_type; }
			set
			{
				this.OnPropertyValueChange("def_task_type");
				this._def_task_type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("acct_id")]
		public int? acct_id
		{
			get { return _acct_id; }
			set
			{
				this.OnPropertyValueChange("acct_id");
				this._acct_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("acct_guid")]
		public string acct_guid
		{
			get { return _acct_guid; }
			set
			{
				this.OnPropertyValueChange("acct_guid");
				this._acct_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("clndr_id")]
		public int? clndr_id
		{
			get { return _clndr_id; }
			set
			{
				this.OnPropertyValueChange("clndr_id");
				this._clndr_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("clndr_guid")]
		public string clndr_guid
		{
			get { return _clndr_guid; }
			set
			{
				this.OnPropertyValueChange("clndr_guid");
				this._clndr_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("week_id")]
		public int? week_id
		{
			get { return _week_id; }
			set
			{
				this.OnPropertyValueChange("week_id");
				this._week_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("update_date")]
		public DateTime? update_date
		{
			get { return _update_date; }
			set
			{
				this.OnPropertyValueChange("update_date");
				this._update_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("critical_drtn_hr_cnt")]
		public decimal? critical_drtn_hr_cnt
		{
			get { return _critical_drtn_hr_cnt; }
			set
			{
				this.OnPropertyValueChange("critical_drtn_hr_cnt");
				this._critical_drtn_hr_cnt = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("critical_path_type")]
		public string critical_path_type
		{
			get { return _critical_path_type; }
			set
			{
				this.OnPropertyValueChange("critical_path_type");
				this._critical_path_type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("start_date")]
		public DateTime? start_date
		{
			get { return _start_date; }
			set
			{
				this.OnPropertyValueChange("start_date");
				this._start_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("end_date")]
		public DateTime? end_date
		{
			get { return _end_date; }
			set
			{
				this.OnPropertyValueChange("end_date");
				this._end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Pro_owners")]
		public int? Pro_owners
		{
			get { return _Pro_owners; }
			set
			{
				this.OnPropertyValueChange("Pro_owners");
				this._Pro_owners = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Pro_manager")]
		public int? Pro_manager
		{
			get { return _Pro_manager; }
			set
			{
				this.OnPropertyValueChange("Pro_manager");
				this._Pro_manager = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Pro_time")]
		public DateTime? Pro_time
		{
			get { return _Pro_time; }
			set
			{
				this.OnPropertyValueChange("Pro_time");
				this._Pro_time = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Pro_general_situation")]
		public string Pro_general_situation
		{
			get { return _Pro_general_situation; }
			set
			{
				this.OnPropertyValueChange("Pro_general_situation");
				this._Pro_general_situation = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Pro_Construction_content")]
		public string Pro_Construction_content
		{
			get { return _Pro_Construction_content; }
			set
			{
				this.OnPropertyValueChange("Pro_Construction_content");
				this._Pro_Construction_content = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Pro_total")]
		public decimal? Pro_total
		{
			get { return _Pro_total; }
			set
			{
				this.OnPropertyValueChange("Pro_total");
				this._Pro_total = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("STATE")]
		public int? STATE
		{
			get { return _STATE; }
			set
			{
				this.OnPropertyValueChange("STATE");
				this._STATE = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("zuzhijigou")]
		public string zuzhijigou
		{
			get { return _zuzhijigou; }
			set
			{
				this.OnPropertyValueChange("zuzhijigou");
				this._zuzhijigou = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("isLiXiang")]
		public int? isLiXiang
		{
			get { return _isLiXiang; }
			set
			{
				this.OnPropertyValueChange("isLiXiang");
				this._isLiXiang = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("adder_sid")]
		public int? adder_sid
		{
			get { return _adder_sid; }
			set
			{
				this.OnPropertyValueChange("adder_sid");
				this._adder_sid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("add_date")]
		public DateTime? add_date
		{
			get { return _add_date; }
			set
			{
				this.OnPropertyValueChange("add_date");
				this._add_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("if_plan")]
		public bool? if_plan
		{
			get { return _if_plan; }
			set
			{
				this.OnPropertyValueChange("if_plan");
				this._if_plan = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LongCode")]
		public string LongCode
		{
			get { return _LongCode; }
			set
			{
				this.OnPropertyValueChange("LongCode");
				this._LongCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("BizAreaId")]
		public Guid? BizAreaId
		{
			get { return _BizAreaId; }
			set
			{
				this.OnPropertyValueChange("BizAreaId");
				this._BizAreaId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Pro_manager_guid")]
		public Guid? Pro_manager_guid
		{
			get { return _Pro_manager_guid; }
			set
			{
				this.OnPropertyValueChange("Pro_manager_guid");
				this._Pro_manager_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Pro_manager_name")]
		public string Pro_manager_name
		{
			get { return _Pro_manager_name; }
			set
			{
				this.OnPropertyValueChange("Pro_manager_name");
				this._Pro_manager_name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Pro_owners_guid")]
		public Guid? Pro_owners_guid
		{
			get { return _Pro_owners_guid; }
			set
			{
				this.OnPropertyValueChange("Pro_owners_guid");
				this._Pro_owners_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Pro_owners_name")]
		public string Pro_owners_name
		{
			get { return _Pro_owners_name; }
			set
			{
				this.OnPropertyValueChange("Pro_owners_name");
				this._Pro_owners_name = value;
			}
		}
		/// <summary>
		/// 管理层级Id
		/// </summary>
		[Field("EpsProjId")]
		public string EpsProjId
		{
			get { return _EpsProjId; }
			set
			{
				this.OnPropertyValueChange("EpsProjId");
				this._EpsProjId = value;
			}
		}
		/// <summary>
		/// 管理层级名称
		/// </summary>
		[Field("EpsProjName")]
		public string EpsProjName
		{
			get { return _EpsProjName; }
			set
			{
				this.OnPropertyValueChange("EpsProjName");
				this._EpsProjName = value;
			}
		}
		/// <summary>
		/// 管理层级类型；0非管理层级，1总公司，2分公司，3项目群，4项目...
		/// </summary>
		[Field("EpsProjType")]
		public int? EpsProjType
		{
			get { return _EpsProjType; }
			set
			{
				this.OnPropertyValueChange("EpsProjType");
				this._EpsProjType = value;
			}
		}
		/// <summary>
		/// _1启用普通项目范围权限,0不启用
		/// </summary>
		[Field("UseOwnProjRight")]
		public int? UseOwnProjRight
		{
			get { return _UseOwnProjRight; }
			set
			{
				this.OnPropertyValueChange("UseOwnProjRight");
				this._UseOwnProjRight = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("est_wt_value")]
		public decimal? est_wt_value
		{
			get { return _est_wt_value; }
			set
			{
				this.OnPropertyValueChange("est_wt_value");
				this._est_wt_value = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Longitude")]
		public decimal? Longitude
		{
			get { return _Longitude; }
			set
			{
				this.OnPropertyValueChange("Longitude");
				this._Longitude = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Latitude")]
		public decimal? Latitude
		{
			get { return _Latitude; }
			set
			{
				this.OnPropertyValueChange("Latitude");
				this._Latitude = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RegHumId")]
		public Guid? RegHumId
		{
			get { return _RegHumId; }
			set
			{
				this.OnPropertyValueChange("RegHumId");
				this._RegHumId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RegHumName")]
		public string RegHumName
		{
			get { return _RegHumName; }
			set
			{
				this.OnPropertyValueChange("RegHumName");
				this._RegHumName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RegDate")]
		public DateTime? RegDate
		{
			get { return _RegDate; }
			set
			{
				this.OnPropertyValueChange("RegDate");
				this._RegDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("update_user")]
		public string update_user
		{
			get { return _update_user; }
			set
			{
				this.OnPropertyValueChange("update_user");
				this._update_user = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("create_date")]
		public DateTime? create_date
		{
			get { return _create_date; }
			set
			{
				this.OnPropertyValueChange("create_date");
				this._create_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("create_user")]
		public string create_user
		{
			get { return _create_user; }
			set
			{
				this.OnPropertyValueChange("create_user");
				this._create_user = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("delete_session_id")]
		public int? delete_session_id
		{
			get { return _delete_session_id; }
			set
			{
				this.OnPropertyValueChange("delete_session_id");
				this._delete_session_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("delete_date")]
		public DateTime? delete_date
		{
			get { return _delete_date; }
			set
			{
				this.OnPropertyValueChange("delete_date");
				this._delete_date = value;
			}
		}
		/// <summary>
		/// 国家
		/// </summary>
		[Field("Country")]
		public string Country
		{
			get { return _Country; }
			set
			{
				this.OnPropertyValueChange("Country");
				this._Country = value;
			}
		}
		/// <summary>
		/// 省
		/// </summary>
		[Field("Province")]
		public string Province
		{
			get { return _Province; }
			set
			{
				this.OnPropertyValueChange("Province");
				this._Province = value;
			}
		}
		/// <summary>
		/// 市
		/// </summary>
		[Field("City")]
		public string City
		{
			get { return _City; }
			set
			{
				this.OnPropertyValueChange("City");
				this._City = value;
			}
		}
		/// <summary>
		/// 县
		/// </summary>
		[Field("County")]
		public string County
		{
			get { return _County; }
			set
			{
				this.OnPropertyValueChange("County");
				this._County = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("EpsProjIcon")]
		public string EpsProjIcon
		{
			get { return _EpsProjIcon; }
			set
			{
				this.OnPropertyValueChange("EpsProjIcon");
				this._EpsProjIcon = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.project_guid,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.project_id,
				_.project_guid,
				_.project_shortname,
				_.project_name,
				_.parent_id,
				_.parent_guid,
				_.remark,
				_.user_sid,
				_.user_guid,
				_.project_type,
				_.est_wt,
				_.obs_sid,
				_.obs_guid,
				_.haschild,
				_.p3ec,
				_.treelevel,
				_.note,
				_.p3ec_project_id,
				_.contract_id,
				_.displayid,
				_.discolor,
				_.project_type_sid,
				_.project_status_sid,
				_.project_address,
				_.target_start_date,
				_.target_end_date,
				_.act_start_date,
				_.act_end_date,
				_.data_date,
				_.compute_end_date,
				_.expect_start_date,
				_.expect_end_date,
				_.unContract_id,
				_.complete_pct,
				_.allow_diy_web,
				_.program_id,
				_.risk_level,
				_.proj_url,
				_.def_duration_type,
				_.def_complete_pct_type,
				_.def_task_type,
				_.acct_id,
				_.acct_guid,
				_.clndr_id,
				_.clndr_guid,
				_.week_id,
				_.update_date,
				_.critical_drtn_hr_cnt,
				_.critical_path_type,
				_.start_date,
				_.end_date,
				_.Pro_owners,
				_.Pro_manager,
				_.Pro_time,
				_.Pro_general_situation,
				_.Pro_Construction_content,
				_.Pro_total,
				_.STATE,
				_.zuzhijigou,
				_.isLiXiang,
				_.adder_sid,
				_.add_date,
				_.if_plan,
				_.LongCode,
				_.BizAreaId,
				_.Pro_manager_guid,
				_.Pro_manager_name,
				_.Pro_owners_guid,
				_.Pro_owners_name,
				_.EpsProjId,
				_.EpsProjName,
				_.EpsProjType,
				_.UseOwnProjRight,
				_.est_wt_value,
				_.Longitude,
				_.Latitude,
				_.RegHumId,
				_.RegHumName,
				_.RegDate,
				_.update_user,
				_.create_date,
				_.create_user,
				_.delete_session_id,
				_.delete_date,
				_.Country,
				_.Province,
				_.City,
				_.County,
				_.EpsProjIcon,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._project_id,
				this._project_guid,
				this._project_shortname,
				this._project_name,
				this._parent_id,
				this._parent_guid,
				this._remark,
				this._user_sid,
				this._user_guid,
				this._project_type,
				this._est_wt,
				this._obs_sid,
				this._obs_guid,
				this._haschild,
				this._p3ec,
				this._treelevel,
				this._note,
				this._p3ec_project_id,
				this._contract_id,
				this._displayid,
				this._discolor,
				this._project_type_sid,
				this._project_status_sid,
				this._project_address,
				this._target_start_date,
				this._target_end_date,
				this._act_start_date,
				this._act_end_date,
				this._data_date,
				this._compute_end_date,
				this._expect_start_date,
				this._expect_end_date,
				this._unContract_id,
				this._complete_pct,
				this._allow_diy_web,
				this._program_id,
				this._risk_level,
				this._proj_url,
				this._def_duration_type,
				this._def_complete_pct_type,
				this._def_task_type,
				this._acct_id,
				this._acct_guid,
				this._clndr_id,
				this._clndr_guid,
				this._week_id,
				this._update_date,
				this._critical_drtn_hr_cnt,
				this._critical_path_type,
				this._start_date,
				this._end_date,
				this._Pro_owners,
				this._Pro_manager,
				this._Pro_time,
				this._Pro_general_situation,
				this._Pro_Construction_content,
				this._Pro_total,
				this._STATE,
				this._zuzhijigou,
				this._isLiXiang,
				this._adder_sid,
				this._add_date,
				this._if_plan,
				this._LongCode,
				this._BizAreaId,
				this._Pro_manager_guid,
				this._Pro_manager_name,
				this._Pro_owners_guid,
				this._Pro_owners_name,
				this._EpsProjId,
				this._EpsProjName,
				this._EpsProjType,
				this._UseOwnProjRight,
				this._est_wt_value,
				this._Longitude,
				this._Latitude,
				this._RegHumId,
				this._RegHumName,
				this._RegDate,
				this._update_user,
				this._create_date,
				this._create_user,
				this._delete_session_id,
				this._delete_date,
				this._Country,
				this._Province,
				this._City,
				this._County,
				this._EpsProjIcon,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "PLN_project");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field project_id = new Field("project_id", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field project_guid = new Field("project_guid", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field project_shortname = new Field("project_shortname", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field project_name = new Field("project_name", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field parent_id = new Field("parent_id", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field parent_guid = new Field("parent_guid", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field remark = new Field("remark", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field user_sid = new Field("user_sid", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field user_guid = new Field("user_guid", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field project_type = new Field("project_type", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field est_wt = new Field("est_wt", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field obs_sid = new Field("obs_sid", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field obs_guid = new Field("obs_guid", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field haschild = new Field("haschild", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field p3ec = new Field("p3ec", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field treelevel = new Field("treelevel", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field note = new Field("note", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field p3ec_project_id = new Field("p3ec_project_id", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field contract_id = new Field("contract_id", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field displayid = new Field("displayid", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field discolor = new Field("discolor", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field project_type_sid = new Field("project_type_sid", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field project_status_sid = new Field("project_status_sid", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field project_address = new Field("project_address", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field target_start_date = new Field("target_start_date", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field target_end_date = new Field("target_end_date", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field act_start_date = new Field("act_start_date", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field act_end_date = new Field("act_end_date", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field data_date = new Field("data_date", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field compute_end_date = new Field("compute_end_date", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field expect_start_date = new Field("expect_start_date", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field expect_end_date = new Field("expect_end_date", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field unContract_id = new Field("unContract_id", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field complete_pct = new Field("complete_pct", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field allow_diy_web = new Field("allow_diy_web", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field program_id = new Field("program_id", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field risk_level = new Field("risk_level", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field proj_url = new Field("proj_url", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field def_duration_type = new Field("def_duration_type", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field def_complete_pct_type = new Field("def_complete_pct_type", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field def_task_type = new Field("def_task_type", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field acct_id = new Field("acct_id", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field acct_guid = new Field("acct_guid", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field clndr_id = new Field("clndr_id", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field clndr_guid = new Field("clndr_guid", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field week_id = new Field("week_id", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field update_date = new Field("update_date", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field critical_drtn_hr_cnt = new Field("critical_drtn_hr_cnt", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field critical_path_type = new Field("critical_path_type", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field start_date = new Field("start_date", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field end_date = new Field("end_date", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Pro_owners = new Field("Pro_owners", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Pro_manager = new Field("Pro_manager", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Pro_time = new Field("Pro_time", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Pro_general_situation = new Field("Pro_general_situation", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Pro_Construction_content = new Field("Pro_Construction_content", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Pro_total = new Field("Pro_total", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field STATE = new Field("STATE", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field zuzhijigou = new Field("zuzhijigou", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field isLiXiang = new Field("isLiXiang", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field adder_sid = new Field("adder_sid", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field add_date = new Field("add_date", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field if_plan = new Field("if_plan", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LongCode = new Field("LongCode", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BizAreaId = new Field("BizAreaId", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Pro_manager_guid = new Field("Pro_manager_guid", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Pro_manager_name = new Field("Pro_manager_name", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Pro_owners_guid = new Field("Pro_owners_guid", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Pro_owners_name = new Field("Pro_owners_name", "PLN_project", "");
			/// <summary>
			/// 管理层级Id
			/// </summary>
			public readonly static Field EpsProjId = new Field("EpsProjId", "PLN_project", "管理层级Id");
			/// <summary>
			/// 管理层级名称
			/// </summary>
			public readonly static Field EpsProjName = new Field("EpsProjName", "PLN_project", "管理层级名称");
			/// <summary>
			/// 管理层级类型；0非管理层级，1总公司，2分公司，3项目群，4项目...
			/// </summary>
			public readonly static Field EpsProjType = new Field("EpsProjType", "PLN_project", "管理层级类型；0非管理层级，1总公司，2分公司，3项目群，4项目...");
			/// <summary>
			/// _1启用普通项目范围权限,0不启用
			/// </summary>
			public readonly static Field UseOwnProjRight = new Field("UseOwnProjRight", "PLN_project", "_1启用普通项目范围权限,0不启用");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field est_wt_value = new Field("est_wt_value", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Longitude = new Field("Longitude", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Latitude = new Field("Latitude", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RegHumId = new Field("RegHumId", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RegHumName = new Field("RegHumName", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RegDate = new Field("RegDate", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field update_user = new Field("update_user", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field create_date = new Field("create_date", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field create_user = new Field("create_user", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field delete_session_id = new Field("delete_session_id", "PLN_project", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field delete_date = new Field("delete_date", "PLN_project", "");
			/// <summary>
			/// 国家
			/// </summary>
			public readonly static Field Country = new Field("Country", "PLN_project", "国家");
			/// <summary>
			/// 省
			/// </summary>
			public readonly static Field Province = new Field("Province", "PLN_project", "省");
			/// <summary>
			/// 市
			/// </summary>
			public readonly static Field City = new Field("City", "PLN_project", "市");
			/// <summary>
			/// 县
			/// </summary>
			public readonly static Field County = new Field("County", "PLN_project", "县");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EpsProjIcon = new Field("EpsProjIcon", "PLN_project", "");
		}
		#endregion
	}
}