//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace Power.SPMEMS.Services.Models
{
	/// <summary>
	/// 实体类DCAREATYPMST。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("DCAREATYPMST")]
	[Serializable]
	[DataContract]
	public partial class DCAREATYPMST : Entity
	{
		#region Model
		private int _AREATYP_NO;
		private int? _ORG_NO;
		private string _VALID_STA;
		private string _AREATYP_ID;
		private string _AREATYP_NAM;
		private string _AREATYP_SHT;
		private string _FSTUSR_ID;
		private DateTime? _FSTUSR_DTM;
		private string _LSTUSR_ID;
		private DateTime? _LSTUSR_DTM;

		/// <summary>
		/// 
		/// </summary>
		[Field("AREATYP_NO")]
		[DataMember]
		public int AREATYP_NO
		{
			get { return _AREATYP_NO; }
			set
			{
				this.OnPropertyValueChange("AREATYP_NO");
				this._AREATYP_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ORG_NO")]
		[DataMember]
		public int? ORG_NO
		{
			get { return _ORG_NO; }
			set
			{
				this.OnPropertyValueChange("ORG_NO");
				this._ORG_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("VALID_STA")]
		[DataMember]
		public string VALID_STA
		{
			get { return _VALID_STA; }
			set
			{
				this.OnPropertyValueChange("VALID_STA");
				this._VALID_STA = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AREATYP_ID")]
		[DataMember]
		public string AREATYP_ID
		{
			get { return _AREATYP_ID; }
			set
			{
				this.OnPropertyValueChange("AREATYP_ID");
				this._AREATYP_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AREATYP_NAM")]
		[DataMember]
		public string AREATYP_NAM
		{
			get { return _AREATYP_NAM; }
			set
			{
				this.OnPropertyValueChange("AREATYP_NAM");
				this._AREATYP_NAM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AREATYP_SHT")]
		[DataMember]
		public string AREATYP_SHT
		{
			get { return _AREATYP_SHT; }
			set
			{
				this.OnPropertyValueChange("AREATYP_SHT");
				this._AREATYP_SHT = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FSTUSR_ID")]
		[DataMember]
		public string FSTUSR_ID
		{
			get { return _FSTUSR_ID; }
			set
			{
				this.OnPropertyValueChange("FSTUSR_ID");
				this._FSTUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FSTUSR_DTM")]
		[DataMember]
		public DateTime? FSTUSR_DTM
		{
			get { return _FSTUSR_DTM; }
			set
			{
				this.OnPropertyValueChange("FSTUSR_DTM");
				this._FSTUSR_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LSTUSR_ID")]
		[DataMember]
		public string LSTUSR_ID
		{
			get { return _LSTUSR_ID; }
			set
			{
				this.OnPropertyValueChange("LSTUSR_ID");
				this._LSTUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LSTUSR_DTM")]
		[DataMember]
		public DateTime? LSTUSR_DTM
		{
			get { return _LSTUSR_DTM; }
			set
			{
				this.OnPropertyValueChange("LSTUSR_DTM");
				this._LSTUSR_DTM = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.AREATYP_NO,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.AREATYP_NO,
				_.ORG_NO,
				_.VALID_STA,
				_.AREATYP_ID,
				_.AREATYP_NAM,
				_.AREATYP_SHT,
				_.FSTUSR_ID,
				_.FSTUSR_DTM,
				_.LSTUSR_ID,
				_.LSTUSR_DTM,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._AREATYP_NO,
				this._ORG_NO,
				this._VALID_STA,
				this._AREATYP_ID,
				this._AREATYP_NAM,
				this._AREATYP_SHT,
				this._FSTUSR_ID,
				this._FSTUSR_DTM,
				this._LSTUSR_ID,
				this._LSTUSR_DTM,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "DCAREATYPMST");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AREATYP_NO = new Field("AREATYP_NO", "DCAREATYPMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ORG_NO = new Field("ORG_NO", "DCAREATYPMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field VALID_STA = new Field("VALID_STA", "DCAREATYPMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AREATYP_ID = new Field("AREATYP_ID", "DCAREATYPMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AREATYP_NAM = new Field("AREATYP_NAM", "DCAREATYPMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AREATYP_SHT = new Field("AREATYP_SHT", "DCAREATYPMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FSTUSR_ID = new Field("FSTUSR_ID", "DCAREATYPMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FSTUSR_DTM = new Field("FSTUSR_DTM", "DCAREATYPMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LSTUSR_ID = new Field("LSTUSR_ID", "DCAREATYPMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LSTUSR_DTM = new Field("LSTUSR_DTM", "DCAREATYPMST", "");
		}
		#endregion
	}
}