//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace Power.SPMEMS.Services.Models
{
	/// <summary>
	/// 实体类DCPROJECTMST。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("DCPROJECTMST")]
	[Serializable]
	[DataContract]
	public partial class DCPROJECTMST : Entity
	{
		#region Model
		private int _PROJECT_NO;
		private int? _ORG_NO;
		private string _PROJECT_ID;
		private string _PROJECT_NAM;
		private string _PRJTYP_NO;
		private string _PRJADR_TYP;
		private string _PRJADR_SHT;
		private string _FSTUSR_ID;
		private DateTime? _FSTUSR_DTM;
		private string _LSTUSR_ID;
		private DateTime? _LSTUSR_DTM;
		private string _PROJECT_DSC;
		private int? _CTMUNIT_NO;
		private int? _AREA_NO;
		private string _AREAEXT_SHT;
		private string _PROJECT_STA;
		private string _EPNUSR_ID;
		private DateTime? _SYNC_DTM;
		private string _BARTZ_ID;
		private string _DAJ_ID;
		private DateTime? _BARGET_DATE;
		private DateTime? _TZGET_DATE;
		private int? _BAR_AMT;
		private int? _SJTZ_AMT;
		private string _PRJJD_ID;
		private string _BAR_USR;
		private string _SJ_DSC;
		private string _BAR_JD;
		private string _PRJ_ID;
		private string _PLAPRJ_USR;
		private string _ENPROJECT_NAM;
		private DateTime? _PLABEG_DTM;
		private DateTime? _PLARK_DTM;
		private DateTime? _ACTRK_DTM;
		private DateTime? _PRJEND_DTM;
		private string _PROJECT_GM;
		private string _PROJECT_NOT;
		private string _TSCSTNAMS;
		private string _TSCSTNOS;
		private int? _YGBAR_AMT;
		private string _FF_TYP;
		private string _BJ_TYP;
		private string _TZ_ID;
		private string _OLD_STA;
		private string _PRO_STA;

		/// <summary>
		/// 
		/// </summary>
		[Field("PROJECT_NO")]
		[DataMember]
		public int PROJECT_NO
		{
			get { return _PROJECT_NO; }
			set
			{
				this.OnPropertyValueChange("PROJECT_NO");
				this._PROJECT_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ORG_NO")]
		[DataMember]
		public int? ORG_NO
		{
			get { return _ORG_NO; }
			set
			{
				this.OnPropertyValueChange("ORG_NO");
				this._ORG_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PROJECT_ID")]
		[DataMember]
		public string PROJECT_ID
		{
			get { return _PROJECT_ID; }
			set
			{
				this.OnPropertyValueChange("PROJECT_ID");
				this._PROJECT_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PROJECT_NAM")]
		[DataMember]
		public string PROJECT_NAM
		{
			get { return _PROJECT_NAM; }
			set
			{
				this.OnPropertyValueChange("PROJECT_NAM");
				this._PROJECT_NAM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PRJTYP_NO")]
		[DataMember]
		public string PRJTYP_NO
		{
			get { return _PRJTYP_NO; }
			set
			{
				this.OnPropertyValueChange("PRJTYP_NO");
				this._PRJTYP_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PRJADR_TYP")]
		[DataMember]
		public string PRJADR_TYP
		{
			get { return _PRJADR_TYP; }
			set
			{
				this.OnPropertyValueChange("PRJADR_TYP");
				this._PRJADR_TYP = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PRJADR_SHT")]
		[DataMember]
		public string PRJADR_SHT
		{
			get { return _PRJADR_SHT; }
			set
			{
				this.OnPropertyValueChange("PRJADR_SHT");
				this._PRJADR_SHT = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FSTUSR_ID")]
		[DataMember]
		public string FSTUSR_ID
		{
			get { return _FSTUSR_ID; }
			set
			{
				this.OnPropertyValueChange("FSTUSR_ID");
				this._FSTUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FSTUSR_DTM")]
		[DataMember]
		public DateTime? FSTUSR_DTM
		{
			get { return _FSTUSR_DTM; }
			set
			{
				this.OnPropertyValueChange("FSTUSR_DTM");
				this._FSTUSR_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LSTUSR_ID")]
		[DataMember]
		public string LSTUSR_ID
		{
			get { return _LSTUSR_ID; }
			set
			{
				this.OnPropertyValueChange("LSTUSR_ID");
				this._LSTUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LSTUSR_DTM")]
		[DataMember]
		public DateTime? LSTUSR_DTM
		{
			get { return _LSTUSR_DTM; }
			set
			{
				this.OnPropertyValueChange("LSTUSR_DTM");
				this._LSTUSR_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PROJECT_DSC")]
		[DataMember]
		public string PROJECT_DSC
		{
			get { return _PROJECT_DSC; }
			set
			{
				this.OnPropertyValueChange("PROJECT_DSC");
				this._PROJECT_DSC = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CTMUNIT_NO")]
		[DataMember]
		public int? CTMUNIT_NO
		{
			get { return _CTMUNIT_NO; }
			set
			{
				this.OnPropertyValueChange("CTMUNIT_NO");
				this._CTMUNIT_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AREA_NO")]
		[DataMember]
		public int? AREA_NO
		{
			get { return _AREA_NO; }
			set
			{
				this.OnPropertyValueChange("AREA_NO");
				this._AREA_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AREAEXT_SHT")]
		[DataMember]
		public string AREAEXT_SHT
		{
			get { return _AREAEXT_SHT; }
			set
			{
				this.OnPropertyValueChange("AREAEXT_SHT");
				this._AREAEXT_SHT = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PROJECT_STA")]
		[DataMember]
		public string PROJECT_STA
		{
			get { return _PROJECT_STA; }
			set
			{
				this.OnPropertyValueChange("PROJECT_STA");
				this._PROJECT_STA = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("EPNUSR_ID")]
		[DataMember]
		public string EPNUSR_ID
		{
			get { return _EPNUSR_ID; }
			set
			{
				this.OnPropertyValueChange("EPNUSR_ID");
				this._EPNUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SYNC_DTM")]
		[DataMember]
		public DateTime? SYNC_DTM
		{
			get { return _SYNC_DTM; }
			set
			{
				this.OnPropertyValueChange("SYNC_DTM");
				this._SYNC_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("BARTZ_ID")]
		[DataMember]
		public string BARTZ_ID
		{
			get { return _BARTZ_ID; }
			set
			{
				this.OnPropertyValueChange("BARTZ_ID");
				this._BARTZ_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DAJ_ID")]
		[DataMember]
		public string DAJ_ID
		{
			get { return _DAJ_ID; }
			set
			{
				this.OnPropertyValueChange("DAJ_ID");
				this._DAJ_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("BARGET_DATE")]
		[DataMember]
		public DateTime? BARGET_DATE
		{
			get { return _BARGET_DATE; }
			set
			{
				this.OnPropertyValueChange("BARGET_DATE");
				this._BARGET_DATE = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TZGET_DATE")]
		[DataMember]
		public DateTime? TZGET_DATE
		{
			get { return _TZGET_DATE; }
			set
			{
				this.OnPropertyValueChange("TZGET_DATE");
				this._TZGET_DATE = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("BAR_AMT")]
		[DataMember]
		public int? BAR_AMT
		{
			get { return _BAR_AMT; }
			set
			{
				this.OnPropertyValueChange("BAR_AMT");
				this._BAR_AMT = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SJTZ_AMT")]
		[DataMember]
		public int? SJTZ_AMT
		{
			get { return _SJTZ_AMT; }
			set
			{
				this.OnPropertyValueChange("SJTZ_AMT");
				this._SJTZ_AMT = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PRJJD_ID")]
		[DataMember]
		public string PRJJD_ID
		{
			get { return _PRJJD_ID; }
			set
			{
				this.OnPropertyValueChange("PRJJD_ID");
				this._PRJJD_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("BAR_USR")]
		[DataMember]
		public string BAR_USR
		{
			get { return _BAR_USR; }
			set
			{
				this.OnPropertyValueChange("BAR_USR");
				this._BAR_USR = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SJ_DSC")]
		[DataMember]
		public string SJ_DSC
		{
			get { return _SJ_DSC; }
			set
			{
				this.OnPropertyValueChange("SJ_DSC");
				this._SJ_DSC = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("BAR_JD")]
		[DataMember]
		public string BAR_JD
		{
			get { return _BAR_JD; }
			set
			{
				this.OnPropertyValueChange("BAR_JD");
				this._BAR_JD = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PRJ_ID")]
		[DataMember]
		public string PRJ_ID
		{
			get { return _PRJ_ID; }
			set
			{
				this.OnPropertyValueChange("PRJ_ID");
				this._PRJ_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PLAPRJ_USR")]
		[DataMember]
		public string PLAPRJ_USR
		{
			get { return _PLAPRJ_USR; }
			set
			{
				this.OnPropertyValueChange("PLAPRJ_USR");
				this._PLAPRJ_USR = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ENPROJECT_NAM")]
		[DataMember]
		public string ENPROJECT_NAM
		{
			get { return _ENPROJECT_NAM; }
			set
			{
				this.OnPropertyValueChange("ENPROJECT_NAM");
				this._ENPROJECT_NAM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PLABEG_DTM")]
		[DataMember]
		public DateTime? PLABEG_DTM
		{
			get { return _PLABEG_DTM; }
			set
			{
				this.OnPropertyValueChange("PLABEG_DTM");
				this._PLABEG_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PLARK_DTM")]
		[DataMember]
		public DateTime? PLARK_DTM
		{
			get { return _PLARK_DTM; }
			set
			{
				this.OnPropertyValueChange("PLARK_DTM");
				this._PLARK_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ACTRK_DTM")]
		[DataMember]
		public DateTime? ACTRK_DTM
		{
			get { return _ACTRK_DTM; }
			set
			{
				this.OnPropertyValueChange("ACTRK_DTM");
				this._ACTRK_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PRJEND_DTM")]
		[DataMember]
		public DateTime? PRJEND_DTM
		{
			get { return _PRJEND_DTM; }
			set
			{
				this.OnPropertyValueChange("PRJEND_DTM");
				this._PRJEND_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PROJECT_GM")]
		[DataMember]
		public string PROJECT_GM
		{
			get { return _PROJECT_GM; }
			set
			{
				this.OnPropertyValueChange("PROJECT_GM");
				this._PROJECT_GM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PROJECT_NOT")]
		[DataMember]
		public string PROJECT_NOT
		{
			get { return _PROJECT_NOT; }
			set
			{
				this.OnPropertyValueChange("PROJECT_NOT");
				this._PROJECT_NOT = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TSCSTNAMS")]
		[DataMember]
		public string TSCSTNAMS
		{
			get { return _TSCSTNAMS; }
			set
			{
				this.OnPropertyValueChange("TSCSTNAMS");
				this._TSCSTNAMS = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TSCSTNOS")]
		[DataMember]
		public string TSCSTNOS
		{
			get { return _TSCSTNOS; }
			set
			{
				this.OnPropertyValueChange("TSCSTNOS");
				this._TSCSTNOS = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("YGBAR_AMT")]
		[DataMember]
		public int? YGBAR_AMT
		{
			get { return _YGBAR_AMT; }
			set
			{
				this.OnPropertyValueChange("YGBAR_AMT");
				this._YGBAR_AMT = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FF_TYP")]
		[DataMember]
		public string FF_TYP
		{
			get { return _FF_TYP; }
			set
			{
				this.OnPropertyValueChange("FF_TYP");
				this._FF_TYP = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("BJ_TYP")]
		[DataMember]
		public string BJ_TYP
		{
			get { return _BJ_TYP; }
			set
			{
				this.OnPropertyValueChange("BJ_TYP");
				this._BJ_TYP = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TZ_ID")]
		[DataMember]
		public string TZ_ID
		{
			get { return _TZ_ID; }
			set
			{
				this.OnPropertyValueChange("TZ_ID");
				this._TZ_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("OLD_STA")]
		[DataMember]
		public string OLD_STA
		{
			get { return _OLD_STA; }
			set
			{
				this.OnPropertyValueChange("OLD_STA");
				this._OLD_STA = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PRO_STA")]
		[DataMember]
		public string PRO_STA
		{
			get { return _PRO_STA; }
			set
			{
				this.OnPropertyValueChange("PRO_STA");
				this._PRO_STA = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.PROJECT_NO,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.PROJECT_NO,
				_.ORG_NO,
				_.PROJECT_ID,
				_.PROJECT_NAM,
				_.PRJTYP_NO,
				_.PRJADR_TYP,
				_.PRJADR_SHT,
				_.FSTUSR_ID,
				_.FSTUSR_DTM,
				_.LSTUSR_ID,
				_.LSTUSR_DTM,
				_.PROJECT_DSC,
				_.CTMUNIT_NO,
				_.AREA_NO,
				_.AREAEXT_SHT,
				_.PROJECT_STA,
				_.EPNUSR_ID,
				_.SYNC_DTM,
				_.BARTZ_ID,
				_.DAJ_ID,
				_.BARGET_DATE,
				_.TZGET_DATE,
				_.BAR_AMT,
				_.SJTZ_AMT,
				_.PRJJD_ID,
				_.BAR_USR,
				_.SJ_DSC,
				_.BAR_JD,
				_.PRJ_ID,
				_.PLAPRJ_USR,
				_.ENPROJECT_NAM,
				_.PLABEG_DTM,
				_.PLARK_DTM,
				_.ACTRK_DTM,
				_.PRJEND_DTM,
				_.PROJECT_GM,
				_.PROJECT_NOT,
				_.TSCSTNAMS,
				_.TSCSTNOS,
				_.YGBAR_AMT,
				_.FF_TYP,
				_.BJ_TYP,
				_.TZ_ID,
				_.OLD_STA,
				_.PRO_STA,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._PROJECT_NO,
				this._ORG_NO,
				this._PROJECT_ID,
				this._PROJECT_NAM,
				this._PRJTYP_NO,
				this._PRJADR_TYP,
				this._PRJADR_SHT,
				this._FSTUSR_ID,
				this._FSTUSR_DTM,
				this._LSTUSR_ID,
				this._LSTUSR_DTM,
				this._PROJECT_DSC,
				this._CTMUNIT_NO,
				this._AREA_NO,
				this._AREAEXT_SHT,
				this._PROJECT_STA,
				this._EPNUSR_ID,
				this._SYNC_DTM,
				this._BARTZ_ID,
				this._DAJ_ID,
				this._BARGET_DATE,
				this._TZGET_DATE,
				this._BAR_AMT,
				this._SJTZ_AMT,
				this._PRJJD_ID,
				this._BAR_USR,
				this._SJ_DSC,
				this._BAR_JD,
				this._PRJ_ID,
				this._PLAPRJ_USR,
				this._ENPROJECT_NAM,
				this._PLABEG_DTM,
				this._PLARK_DTM,
				this._ACTRK_DTM,
				this._PRJEND_DTM,
				this._PROJECT_GM,
				this._PROJECT_NOT,
				this._TSCSTNAMS,
				this._TSCSTNOS,
				this._YGBAR_AMT,
				this._FF_TYP,
				this._BJ_TYP,
				this._TZ_ID,
				this._OLD_STA,
				this._PRO_STA,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "DCPROJECTMST");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PROJECT_NO = new Field("PROJECT_NO", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ORG_NO = new Field("ORG_NO", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PROJECT_ID = new Field("PROJECT_ID", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PROJECT_NAM = new Field("PROJECT_NAM", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PRJTYP_NO = new Field("PRJTYP_NO", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PRJADR_TYP = new Field("PRJADR_TYP", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PRJADR_SHT = new Field("PRJADR_SHT", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FSTUSR_ID = new Field("FSTUSR_ID", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FSTUSR_DTM = new Field("FSTUSR_DTM", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LSTUSR_ID = new Field("LSTUSR_ID", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LSTUSR_DTM = new Field("LSTUSR_DTM", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PROJECT_DSC = new Field("PROJECT_DSC", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CTMUNIT_NO = new Field("CTMUNIT_NO", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AREA_NO = new Field("AREA_NO", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AREAEXT_SHT = new Field("AREAEXT_SHT", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PROJECT_STA = new Field("PROJECT_STA", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EPNUSR_ID = new Field("EPNUSR_ID", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SYNC_DTM = new Field("SYNC_DTM", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BARTZ_ID = new Field("BARTZ_ID", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DAJ_ID = new Field("DAJ_ID", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BARGET_DATE = new Field("BARGET_DATE", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TZGET_DATE = new Field("TZGET_DATE", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BAR_AMT = new Field("BAR_AMT", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SJTZ_AMT = new Field("SJTZ_AMT", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PRJJD_ID = new Field("PRJJD_ID", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BAR_USR = new Field("BAR_USR", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SJ_DSC = new Field("SJ_DSC", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BAR_JD = new Field("BAR_JD", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PRJ_ID = new Field("PRJ_ID", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PLAPRJ_USR = new Field("PLAPRJ_USR", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ENPROJECT_NAM = new Field("ENPROJECT_NAM", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PLABEG_DTM = new Field("PLABEG_DTM", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PLARK_DTM = new Field("PLARK_DTM", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ACTRK_DTM = new Field("ACTRK_DTM", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PRJEND_DTM = new Field("PRJEND_DTM", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PROJECT_GM = new Field("PROJECT_GM", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PROJECT_NOT = new Field("PROJECT_NOT", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TSCSTNAMS = new Field("TSCSTNAMS", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TSCSTNOS = new Field("TSCSTNOS", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field YGBAR_AMT = new Field("YGBAR_AMT", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FF_TYP = new Field("FF_TYP", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BJ_TYP = new Field("BJ_TYP", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TZ_ID = new Field("TZ_ID", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OLD_STA = new Field("OLD_STA", "DCPROJECTMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PRO_STA = new Field("PRO_STA", "DCPROJECTMST", "");
		}
		#endregion
	}
}