//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace Power.SPMEMS.Services.Models
{
	/// <summary>
	/// 实体类DCSKLMST。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("DCSKLMST")]
	[Serializable]
	[DataContract]
	public partial class DCSKLMST : Entity
	{
		#region Model
		private int _SKL_NO;
		private int? _ORG_NO;
		private string _VALID_STA;
		private string _SKL_ID;
		private string _SKL_NAM;
		private int? _CST_NO;
		private string _USR_ID;
		private string _SHORT_ID;
		private int? _SORT_NUM;
		private string _SKL_NOT;
		private string _FSTUSR_ID;
		private DateTime? _FSTUSR_DTM;
		private string _LSTUSR_ID;
		private DateTime? _LSTUSR_DTM;
		private string _ISMUSR;
		private string _CTPUSR_ID;
		private string _PRJUSR_ID;
		private int? _PV_PEC;
		private string _ZYDM;

		/// <summary>
		/// 
		/// </summary>
		[Field("SKL_NO")]
		[DataMember]
		public int SKL_NO
		{
			get { return _SKL_NO; }
			set
			{
				this.OnPropertyValueChange("SKL_NO");
				this._SKL_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ORG_NO")]
		[DataMember]
		public int? ORG_NO
		{
			get { return _ORG_NO; }
			set
			{
				this.OnPropertyValueChange("ORG_NO");
				this._ORG_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("VALID_STA")]
		[DataMember]
		public string VALID_STA
		{
			get { return _VALID_STA; }
			set
			{
				this.OnPropertyValueChange("VALID_STA");
				this._VALID_STA = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SKL_ID")]
		[DataMember]
		public string SKL_ID
		{
			get { return _SKL_ID; }
			set
			{
				this.OnPropertyValueChange("SKL_ID");
				this._SKL_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SKL_NAM")]
		[DataMember]
		public string SKL_NAM
		{
			get { return _SKL_NAM; }
			set
			{
				this.OnPropertyValueChange("SKL_NAM");
				this._SKL_NAM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CST_NO")]
		[DataMember]
		public int? CST_NO
		{
			get { return _CST_NO; }
			set
			{
				this.OnPropertyValueChange("CST_NO");
				this._CST_NO = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("USR_ID")]
		[DataMember]
		public string USR_ID
		{
			get { return _USR_ID; }
			set
			{
				this.OnPropertyValueChange("USR_ID");
				this._USR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SHORT_ID")]
		[DataMember]
		public string SHORT_ID
		{
			get { return _SHORT_ID; }
			set
			{
				this.OnPropertyValueChange("SHORT_ID");
				this._SHORT_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SORT_NUM")]
		[DataMember]
		public int? SORT_NUM
		{
			get { return _SORT_NUM; }
			set
			{
				this.OnPropertyValueChange("SORT_NUM");
				this._SORT_NUM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SKL_NOT")]
		[DataMember]
		public string SKL_NOT
		{
			get { return _SKL_NOT; }
			set
			{
				this.OnPropertyValueChange("SKL_NOT");
				this._SKL_NOT = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FSTUSR_ID")]
		[DataMember]
		public string FSTUSR_ID
		{
			get { return _FSTUSR_ID; }
			set
			{
				this.OnPropertyValueChange("FSTUSR_ID");
				this._FSTUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FSTUSR_DTM")]
		[DataMember]
		public DateTime? FSTUSR_DTM
		{
			get { return _FSTUSR_DTM; }
			set
			{
				this.OnPropertyValueChange("FSTUSR_DTM");
				this._FSTUSR_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LSTUSR_ID")]
		[DataMember]
		public string LSTUSR_ID
		{
			get { return _LSTUSR_ID; }
			set
			{
				this.OnPropertyValueChange("LSTUSR_ID");
				this._LSTUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LSTUSR_DTM")]
		[DataMember]
		public DateTime? LSTUSR_DTM
		{
			get { return _LSTUSR_DTM; }
			set
			{
				this.OnPropertyValueChange("LSTUSR_DTM");
				this._LSTUSR_DTM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ISMUSR")]
		[DataMember]
		public string ISMUSR
		{
			get { return _ISMUSR; }
			set
			{
				this.OnPropertyValueChange("ISMUSR");
				this._ISMUSR = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CTPUSR_ID")]
		[DataMember]
		public string CTPUSR_ID
		{
			get { return _CTPUSR_ID; }
			set
			{
				this.OnPropertyValueChange("CTPUSR_ID");
				this._CTPUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PRJUSR_ID")]
		[DataMember]
		public string PRJUSR_ID
		{
			get { return _PRJUSR_ID; }
			set
			{
				this.OnPropertyValueChange("PRJUSR_ID");
				this._PRJUSR_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PV_PEC")]
		[DataMember]
		public int? PV_PEC
		{
			get { return _PV_PEC; }
			set
			{
				this.OnPropertyValueChange("PV_PEC");
				this._PV_PEC = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ZYDM")]
		[DataMember]
		public string ZYDM
		{
			get { return _ZYDM; }
			set
			{
				this.OnPropertyValueChange("ZYDM");
				this._ZYDM = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.SKL_NO,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.SKL_NO,
				_.ORG_NO,
				_.VALID_STA,
				_.SKL_ID,
				_.SKL_NAM,
				_.CST_NO,
				_.USR_ID,
				_.SHORT_ID,
				_.SORT_NUM,
				_.SKL_NOT,
				_.FSTUSR_ID,
				_.FSTUSR_DTM,
				_.LSTUSR_ID,
				_.LSTUSR_DTM,
				_.ISMUSR,
				_.CTPUSR_ID,
				_.PRJUSR_ID,
				_.PV_PEC,
				_.ZYDM,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._SKL_NO,
				this._ORG_NO,
				this._VALID_STA,
				this._SKL_ID,
				this._SKL_NAM,
				this._CST_NO,
				this._USR_ID,
				this._SHORT_ID,
				this._SORT_NUM,
				this._SKL_NOT,
				this._FSTUSR_ID,
				this._FSTUSR_DTM,
				this._LSTUSR_ID,
				this._LSTUSR_DTM,
				this._ISMUSR,
				this._CTPUSR_ID,
				this._PRJUSR_ID,
				this._PV_PEC,
				this._ZYDM,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "DCSKLMST");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SKL_NO = new Field("SKL_NO", "DCSKLMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ORG_NO = new Field("ORG_NO", "DCSKLMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field VALID_STA = new Field("VALID_STA", "DCSKLMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SKL_ID = new Field("SKL_ID", "DCSKLMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SKL_NAM = new Field("SKL_NAM", "DCSKLMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CST_NO = new Field("CST_NO", "DCSKLMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field USR_ID = new Field("USR_ID", "DCSKLMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SHORT_ID = new Field("SHORT_ID", "DCSKLMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SORT_NUM = new Field("SORT_NUM", "DCSKLMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SKL_NOT = new Field("SKL_NOT", "DCSKLMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FSTUSR_ID = new Field("FSTUSR_ID", "DCSKLMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FSTUSR_DTM = new Field("FSTUSR_DTM", "DCSKLMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LSTUSR_ID = new Field("LSTUSR_ID", "DCSKLMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LSTUSR_DTM = new Field("LSTUSR_DTM", "DCSKLMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ISMUSR = new Field("ISMUSR", "DCSKLMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CTPUSR_ID = new Field("CTPUSR_ID", "DCSKLMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PRJUSR_ID = new Field("PRJUSR_ID", "DCSKLMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PV_PEC = new Field("PV_PEC", "DCSKLMST", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ZYDM = new Field("ZYDM", "DCSKLMST", "");
		}
		#endregion
	}
}