//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace Power.SPMEMS.Services.Models
{
	/// <summary>
	/// 实体类NPS_PUR_EPCEquipInOutCount。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("NPS_PUR_EPCEquipInOutCount")]
	[Serializable]
	public partial class NPS_PUR_EPCEquipInOutCount : Entity
	{
		#region Model
		private Guid _ID;
		private string _Code;
		private string _Title;
		private string _CellCode;
		private string _Version;
		private string _PurchaseNo;
		private string _PurchaseName;
		private string _PurCode;
		private string _ConCode;
		private string _SubcontName;
		private float? _ConAllMoney;
		private string _Unit;
		private float? _Num;
		private float? _WNum;
		private float? _WRate;
		private float? _InNum;
		private float? _OutNum;
		private float? _OutRate;
		private float? _InOutRate;
		private float? _InMoney;
		private float? _OutMoney;
		private float? _InRate;
		private Guid? _BizAreaId;
		private int? _Sequ;
		private int? _Status;
		private Guid? _RegHumId;
		private string _RegHumName;
		private DateTime? _RegDate;
		private Guid? _RegPosiId;
		private Guid? _RegDeptId;
		private Guid? _EpsProjId;
		private Guid? _RecycleHumId;
		private Guid? _UpdHumId;
		private string _UpdHumName;
		private DateTime? _UpdDate;
		private Guid? _ApprHumId;
		private string _ApprHumName;
		private DateTime? _ApprDate;
		private string _Remark;
		private Guid? _OwnProjId;
		private string _OwnProjName;
		private string _EpsProjCode;
		private string _EpsProjName;
		private Guid? _CompanyID;
		private string _CompanyCode;
		private string _CompanyName;
		private string _ProfName;

		/// <summary>
		/// 主键
		/// </summary>
		[Field("ID")]
		public Guid ID
		{
			get { return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 编号
		/// </summary>
		[Field("Code")]
		public string Code
		{
			get { return _Code; }
			set
			{
				this.OnPropertyValueChange("Code");
				this._Code = value;
			}
		}
		/// <summary>
		/// 标题
		/// </summary>
		[Field("Title")]
		public string Title
		{
			get { return _Title; }
			set
			{
				this.OnPropertyValueChange("Title");
				this._Title = value;
			}
		}
		/// <summary>
		/// 主项
		/// </summary>
		[Field("CellCode")]
		public string CellCode
		{
			get { return _CellCode; }
			set
			{
				this.OnPropertyValueChange("CellCode");
				this._CellCode = value;
			}
		}
		/// <summary>
		/// 请购版本
		/// </summary>
		[Field("Version")]
		public string Version
		{
			get { return _Version; }
			set
			{
				this.OnPropertyValueChange("Version");
				this._Version = value;
			}
		}
		/// <summary>
		/// 请购文件编号
		/// </summary>
		[Field("PurchaseNo")]
		public string PurchaseNo
		{
			get { return _PurchaseNo; }
			set
			{
				this.OnPropertyValueChange("PurchaseNo");
				this._PurchaseNo = value;
			}
		}
		/// <summary>
		/// 请购文件名称
		/// </summary>
		[Field("PurchaseName")]
		public string PurchaseName
		{
			get { return _PurchaseName; }
			set
			{
				this.OnPropertyValueChange("PurchaseName");
				this._PurchaseName = value;
			}
		}
		/// <summary>
		/// 订单编号
		/// </summary>
		[Field("PurCode")]
		public string PurCode
		{
			get { return _PurCode; }
			set
			{
				this.OnPropertyValueChange("PurCode");
				this._PurCode = value;
			}
		}
		/// <summary>
		/// 合同编号
		/// </summary>
		[Field("ConCode")]
		public string ConCode
		{
			get { return _ConCode; }
			set
			{
				this.OnPropertyValueChange("ConCode");
				this._ConCode = value;
			}
		}
		/// <summary>
		/// 供应商名称
		/// </summary>
		[Field("SubcontName")]
		public string SubcontName
		{
			get { return _SubcontName; }
			set
			{
				this.OnPropertyValueChange("SubcontName");
				this._SubcontName = value;
			}
		}
		/// <summary>
		/// 合同总价
		/// </summary>
		[Field("ConAllMoney")]
		public float? ConAllMoney
		{
			get { return _ConAllMoney; }
			set
			{
				this.OnPropertyValueChange("ConAllMoney");
				this._ConAllMoney = value;
			}
		}
		/// <summary>
		/// 单位
		/// </summary>
		[Field("Unit")]
		public string Unit
		{
			get { return _Unit; }
			set
			{
				this.OnPropertyValueChange("Unit");
				this._Unit = value;
			}
		}
		/// <summary>
		/// 请购数量
		/// </summary>
		[Field("Num")]
		public float? Num
		{
			get { return _Num; }
			set
			{
				this.OnPropertyValueChange("Num");
				this._Num = value;
			}
		}
		/// <summary>
		/// 已放行数量
		/// </summary>
		[Field("WNum")]
		public float? WNum
		{
			get { return _WNum; }
			set
			{
				this.OnPropertyValueChange("WNum");
				this._WNum = value;
			}
		}
		/// <summary>
		/// 已放行比例
		/// </summary>
		[Field("WRate")]
		public float? WRate
		{
			get { return _WRate; }
			set
			{
				this.OnPropertyValueChange("WRate");
				this._WRate = value;
			}
		}
		/// <summary>
		/// 已入库数量
		/// </summary>
		[Field("InNum")]
		public float? InNum
		{
			get { return _InNum; }
			set
			{
				this.OnPropertyValueChange("InNum");
				this._InNum = value;
			}
		}
		/// <summary>
		/// 已出库数量
		/// </summary>
		[Field("OutNum")]
		public float? OutNum
		{
			get { return _OutNum; }
			set
			{
				this.OnPropertyValueChange("OutNum");
				this._OutNum = value;
			}
		}
		/// <summary>
		/// 已出库比例
		/// </summary>
		[Field("OutRate")]
		public float? OutRate
		{
			get { return _OutRate; }
			set
			{
				this.OnPropertyValueChange("OutRate");
				this._OutRate = value;
			}
		}
		/// <summary>
		/// 出入库比例
		/// </summary>
		[Field("InOutRate")]
		public float? InOutRate
		{
			get { return _InOutRate; }
			set
			{
				this.OnPropertyValueChange("InOutRate");
				this._InOutRate = value;
			}
		}
		/// <summary>
		/// 已入库成本
		/// </summary>
		[Field("InMoney")]
		public float? InMoney
		{
			get { return _InMoney; }
			set
			{
				this.OnPropertyValueChange("InMoney");
				this._InMoney = value;
			}
		}
		/// <summary>
		/// 已出库成本
		/// </summary>
		[Field("OutMoney")]
		public float? OutMoney
		{
			get { return _OutMoney; }
			set
			{
				this.OnPropertyValueChange("OutMoney");
				this._OutMoney = value;
			}
		}
		/// <summary>
		/// 已入库比例
		/// </summary>
		[Field("InRate")]
		public float? InRate
		{
			get { return _InRate; }
			set
			{
				this.OnPropertyValueChange("InRate");
				this._InRate = value;
			}
		}
		/// <summary>
		/// 数据录入业务域Id
		/// </summary>
		[Field("BizAreaId")]
		public Guid? BizAreaId
		{
			get { return _BizAreaId; }
			set
			{
				this.OnPropertyValueChange("BizAreaId");
				this._BizAreaId = value;
			}
		}
		/// <summary>
		/// 序号
		/// </summary>
		[Field("Sequ")]
		public int? Sequ
		{
			get { return _Sequ; }
			set
			{
				this.OnPropertyValueChange("Sequ");
				this._Sequ = value;
			}
		}
		/// <summary>
		/// 表单状态
		/// </summary>
		[Field("Status")]
		public int? Status
		{
			get { return _Status; }
			set
			{
				this.OnPropertyValueChange("Status");
				this._Status = value;
			}
		}
		/// <summary>
		/// 录入人Id
		/// </summary>
		[Field("RegHumId")]
		public Guid? RegHumId
		{
			get { return _RegHumId; }
			set
			{
				this.OnPropertyValueChange("RegHumId");
				this._RegHumId = value;
			}
		}
		/// <summary>
		/// 录入人名称
		/// </summary>
		[Field("RegHumName")]
		public string RegHumName
		{
			get { return _RegHumName; }
			set
			{
				this.OnPropertyValueChange("RegHumName");
				this._RegHumName = value;
			}
		}
		/// <summary>
		/// 录入日期
		/// </summary>
		[Field("RegDate")]
		public DateTime? RegDate
		{
			get { return _RegDate; }
			set
			{
				this.OnPropertyValueChange("RegDate");
				this._RegDate = value;
			}
		}
		/// <summary>
		/// 录入人岗位Id
		/// </summary>
		[Field("RegPosiId")]
		public Guid? RegPosiId
		{
			get { return _RegPosiId; }
			set
			{
				this.OnPropertyValueChange("RegPosiId");
				this._RegPosiId = value;
			}
		}
		/// <summary>
		/// 录入人部门Id
		/// </summary>
		[Field("RegDeptId")]
		public Guid? RegDeptId
		{
			get { return _RegDeptId; }
			set
			{
				this.OnPropertyValueChange("RegDeptId");
				this._RegDeptId = value;
			}
		}
		/// <summary>
		/// 记录所属EPS节点Id
		/// </summary>
		[Field("EpsProjId")]
		public Guid? EpsProjId
		{
			get { return _EpsProjId; }
			set
			{
				this.OnPropertyValueChange("EpsProjId");
				this._EpsProjId = value;
			}
		}
		/// <summary>
		/// 删除人Id
		/// </summary>
		[Field("RecycleHumId")]
		public Guid? RecycleHumId
		{
			get { return _RecycleHumId; }
			set
			{
				this.OnPropertyValueChange("RecycleHumId");
				this._RecycleHumId = value;
			}
		}
		/// <summary>
		/// 最后更新人Id
		/// </summary>
		[Field("UpdHumId")]
		public Guid? UpdHumId
		{
			get { return _UpdHumId; }
			set
			{
				this.OnPropertyValueChange("UpdHumId");
				this._UpdHumId = value;
			}
		}
		/// <summary>
		/// 最后更新人名称
		/// </summary>
		[Field("UpdHumName")]
		public string UpdHumName
		{
			get { return _UpdHumName; }
			set
			{
				this.OnPropertyValueChange("UpdHumName");
				this._UpdHumName = value;
			}
		}
		/// <summary>
		/// 最后更新日期
		/// </summary>
		[Field("UpdDate")]
		public DateTime? UpdDate
		{
			get { return _UpdDate; }
			set
			{
				this.OnPropertyValueChange("UpdDate");
				this._UpdDate = value;
			}
		}
		/// <summary>
		/// 批准人Id
		/// </summary>
		[Field("ApprHumId")]
		public Guid? ApprHumId
		{
			get { return _ApprHumId; }
			set
			{
				this.OnPropertyValueChange("ApprHumId");
				this._ApprHumId = value;
			}
		}
		/// <summary>
		/// 批准人名称
		/// </summary>
		[Field("ApprHumName")]
		public string ApprHumName
		{
			get { return _ApprHumName; }
			set
			{
				this.OnPropertyValueChange("ApprHumName");
				this._ApprHumName = value;
			}
		}
		/// <summary>
		/// 批准日期
		/// </summary>
		[Field("ApprDate")]
		public DateTime? ApprDate
		{
			get { return _ApprDate; }
			set
			{
				this.OnPropertyValueChange("ApprDate");
				this._ApprDate = value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get { return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 所属项目Id
		/// </summary>
		[Field("OwnProjId")]
		public Guid? OwnProjId
		{
			get { return _OwnProjId; }
			set
			{
				this.OnPropertyValueChange("OwnProjId");
				this._OwnProjId = value;
			}
		}
		/// <summary>
		/// 管理层级名称
		/// </summary>
		[Field("OwnProjName")]
		public string OwnProjName
		{
			get { return _OwnProjName; }
			set
			{
				this.OnPropertyValueChange("OwnProjName");
				this._OwnProjName = value;
			}
		}
		/// <summary>
		/// EPS编号
		/// </summary>
		[Field("EpsProjCode")]
		public string EpsProjCode
		{
			get { return _EpsProjCode; }
			set
			{
				this.OnPropertyValueChange("EpsProjCode");
				this._EpsProjCode = value;
			}
		}
		/// <summary>
		/// EPS名称
		/// </summary>
		[Field("EpsProjName")]
		public string EpsProjName
		{
			get { return _EpsProjName; }
			set
			{
				this.OnPropertyValueChange("EpsProjName");
				this._EpsProjName = value;
			}
		}
		/// <summary>
		/// 单位ID
		/// </summary>
		[Field("CompanyID")]
		public Guid? CompanyID
		{
			get { return _CompanyID; }
			set
			{
				this.OnPropertyValueChange("CompanyID");
				this._CompanyID = value;
			}
		}
		/// <summary>
		/// 单位编号
		/// </summary>
		[Field("CompanyCode")]
		public string CompanyCode
		{
			get { return _CompanyCode; }
			set
			{
				this.OnPropertyValueChange("CompanyCode");
				this._CompanyCode = value;
			}
		}
		/// <summary>
		/// 单位名称
		/// </summary>
		[Field("CompanyName")]
		public string CompanyName
		{
			get { return _CompanyName; }
			set
			{
				this.OnPropertyValueChange("CompanyName");
				this._CompanyName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ProfName")]
		public string ProfName
		{
			get { return _ProfName; }
			set
			{
				this.OnPropertyValueChange("ProfName");
				this._ProfName = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.Code,
				_.Title,
				_.CellCode,
				_.Version,
				_.PurchaseNo,
				_.PurchaseName,
				_.PurCode,
				_.ConCode,
				_.SubcontName,
				_.ConAllMoney,
				_.Unit,
				_.Num,
				_.WNum,
				_.WRate,
				_.InNum,
				_.OutNum,
				_.OutRate,
				_.InOutRate,
				_.InMoney,
				_.OutMoney,
				_.InRate,
				_.BizAreaId,
				_.Sequ,
				_.Status,
				_.RegHumId,
				_.RegHumName,
				_.RegDate,
				_.RegPosiId,
				_.RegDeptId,
				_.EpsProjId,
				_.RecycleHumId,
				_.UpdHumId,
				_.UpdHumName,
				_.UpdDate,
				_.ApprHumId,
				_.ApprHumName,
				_.ApprDate,
				_.Remark,
				_.OwnProjId,
				_.OwnProjName,
				_.EpsProjCode,
				_.EpsProjName,
				_.CompanyID,
				_.CompanyCode,
				_.CompanyName,
				_.ProfName,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._Code,
				this._Title,
				this._CellCode,
				this._Version,
				this._PurchaseNo,
				this._PurchaseName,
				this._PurCode,
				this._ConCode,
				this._SubcontName,
				this._ConAllMoney,
				this._Unit,
				this._Num,
				this._WNum,
				this._WRate,
				this._InNum,
				this._OutNum,
				this._OutRate,
				this._InOutRate,
				this._InMoney,
				this._OutMoney,
				this._InRate,
				this._BizAreaId,
				this._Sequ,
				this._Status,
				this._RegHumId,
				this._RegHumName,
				this._RegDate,
				this._RegPosiId,
				this._RegDeptId,
				this._EpsProjId,
				this._RecycleHumId,
				this._UpdHumId,
				this._UpdHumName,
				this._UpdDate,
				this._ApprHumId,
				this._ApprHumName,
				this._ApprDate,
				this._Remark,
				this._OwnProjId,
				this._OwnProjName,
				this._EpsProjCode,
				this._EpsProjName,
				this._CompanyID,
				this._CompanyCode,
				this._CompanyName,
				this._ProfName,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "NPS_PUR_EPCEquipInOutCount");
			/// <summary>
			/// 主键
			/// </summary>
			public readonly static Field ID = new Field("ID", "NPS_PUR_EPCEquipInOutCount", "主键");
			/// <summary>
			/// 编号
			/// </summary>
			public readonly static Field Code = new Field("Code", "NPS_PUR_EPCEquipInOutCount", "编号");
			/// <summary>
			/// 标题
			/// </summary>
			public readonly static Field Title = new Field("Title", "NPS_PUR_EPCEquipInOutCount", "标题");
			/// <summary>
			/// 主项
			/// </summary>
			public readonly static Field CellCode = new Field("CellCode", "NPS_PUR_EPCEquipInOutCount", "主项");
			/// <summary>
			/// 请购版本
			/// </summary>
			public readonly static Field Version = new Field("Version", "NPS_PUR_EPCEquipInOutCount", "请购版本");
			/// <summary>
			/// 请购文件编号
			/// </summary>
			public readonly static Field PurchaseNo = new Field("PurchaseNo", "NPS_PUR_EPCEquipInOutCount", "请购文件编号");
			/// <summary>
			/// 请购文件名称
			/// </summary>
			public readonly static Field PurchaseName = new Field("PurchaseName", "NPS_PUR_EPCEquipInOutCount", "请购文件名称");
			/// <summary>
			/// 订单编号
			/// </summary>
			public readonly static Field PurCode = new Field("PurCode", "NPS_PUR_EPCEquipInOutCount", "订单编号");
			/// <summary>
			/// 合同编号
			/// </summary>
			public readonly static Field ConCode = new Field("ConCode", "NPS_PUR_EPCEquipInOutCount", "合同编号");
			/// <summary>
			/// 供应商名称
			/// </summary>
			public readonly static Field SubcontName = new Field("SubcontName", "NPS_PUR_EPCEquipInOutCount", "供应商名称");
			/// <summary>
			/// 合同总价
			/// </summary>
			public readonly static Field ConAllMoney = new Field("ConAllMoney", "NPS_PUR_EPCEquipInOutCount", "合同总价");
			/// <summary>
			/// 单位
			/// </summary>
			public readonly static Field Unit = new Field("Unit", "NPS_PUR_EPCEquipInOutCount", "单位");
			/// <summary>
			/// 请购数量
			/// </summary>
			public readonly static Field Num = new Field("Num", "NPS_PUR_EPCEquipInOutCount", "请购数量");
			/// <summary>
			/// 已放行数量
			/// </summary>
			public readonly static Field WNum = new Field("WNum", "NPS_PUR_EPCEquipInOutCount", "已放行数量");
			/// <summary>
			/// 已放行比例
			/// </summary>
			public readonly static Field WRate = new Field("WRate", "NPS_PUR_EPCEquipInOutCount", "已放行比例");
			/// <summary>
			/// 已入库数量
			/// </summary>
			public readonly static Field InNum = new Field("InNum", "NPS_PUR_EPCEquipInOutCount", "已入库数量");
			/// <summary>
			/// 已出库数量
			/// </summary>
			public readonly static Field OutNum = new Field("OutNum", "NPS_PUR_EPCEquipInOutCount", "已出库数量");
			/// <summary>
			/// 已出库比例
			/// </summary>
			public readonly static Field OutRate = new Field("OutRate", "NPS_PUR_EPCEquipInOutCount", "已出库比例");
			/// <summary>
			/// 出入库比例
			/// </summary>
			public readonly static Field InOutRate = new Field("InOutRate", "NPS_PUR_EPCEquipInOutCount", "出入库比例");
			/// <summary>
			/// 已入库成本
			/// </summary>
			public readonly static Field InMoney = new Field("InMoney", "NPS_PUR_EPCEquipInOutCount", "已入库成本");
			/// <summary>
			/// 已出库成本
			/// </summary>
			public readonly static Field OutMoney = new Field("OutMoney", "NPS_PUR_EPCEquipInOutCount", "已出库成本");
			/// <summary>
			/// 已入库比例
			/// </summary>
			public readonly static Field InRate = new Field("InRate", "NPS_PUR_EPCEquipInOutCount", "已入库比例");
			/// <summary>
			/// 数据录入业务域Id
			/// </summary>
			public readonly static Field BizAreaId = new Field("BizAreaId", "NPS_PUR_EPCEquipInOutCount", "数据录入业务域Id");
			/// <summary>
			/// 序号
			/// </summary>
			public readonly static Field Sequ = new Field("Sequ", "NPS_PUR_EPCEquipInOutCount", "序号");
			/// <summary>
			/// 表单状态
			/// </summary>
			public readonly static Field Status = new Field("Status", "NPS_PUR_EPCEquipInOutCount", "表单状态");
			/// <summary>
			/// 录入人Id
			/// </summary>
			public readonly static Field RegHumId = new Field("RegHumId", "NPS_PUR_EPCEquipInOutCount", "录入人Id");
			/// <summary>
			/// 录入人名称
			/// </summary>
			public readonly static Field RegHumName = new Field("RegHumName", "NPS_PUR_EPCEquipInOutCount", "录入人名称");
			/// <summary>
			/// 录入日期
			/// </summary>
			public readonly static Field RegDate = new Field("RegDate", "NPS_PUR_EPCEquipInOutCount", "录入日期");
			/// <summary>
			/// 录入人岗位Id
			/// </summary>
			public readonly static Field RegPosiId = new Field("RegPosiId", "NPS_PUR_EPCEquipInOutCount", "录入人岗位Id");
			/// <summary>
			/// 录入人部门Id
			/// </summary>
			public readonly static Field RegDeptId = new Field("RegDeptId", "NPS_PUR_EPCEquipInOutCount", "录入人部门Id");
			/// <summary>
			/// 记录所属EPS节点Id
			/// </summary>
			public readonly static Field EpsProjId = new Field("EpsProjId", "NPS_PUR_EPCEquipInOutCount", "记录所属EPS节点Id");
			/// <summary>
			/// 删除人Id
			/// </summary>
			public readonly static Field RecycleHumId = new Field("RecycleHumId", "NPS_PUR_EPCEquipInOutCount", "删除人Id");
			/// <summary>
			/// 最后更新人Id
			/// </summary>
			public readonly static Field UpdHumId = new Field("UpdHumId", "NPS_PUR_EPCEquipInOutCount", "最后更新人Id");
			/// <summary>
			/// 最后更新人名称
			/// </summary>
			public readonly static Field UpdHumName = new Field("UpdHumName", "NPS_PUR_EPCEquipInOutCount", "最后更新人名称");
			/// <summary>
			/// 最后更新日期
			/// </summary>
			public readonly static Field UpdDate = new Field("UpdDate", "NPS_PUR_EPCEquipInOutCount", "最后更新日期");
			/// <summary>
			/// 批准人Id
			/// </summary>
			public readonly static Field ApprHumId = new Field("ApprHumId", "NPS_PUR_EPCEquipInOutCount", "批准人Id");
			/// <summary>
			/// 批准人名称
			/// </summary>
			public readonly static Field ApprHumName = new Field("ApprHumName", "NPS_PUR_EPCEquipInOutCount", "批准人名称");
			/// <summary>
			/// 批准日期
			/// </summary>
			public readonly static Field ApprDate = new Field("ApprDate", "NPS_PUR_EPCEquipInOutCount", "批准日期");
			/// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "NPS_PUR_EPCEquipInOutCount", "备注");
			/// <summary>
			/// 所属项目Id
			/// </summary>
			public readonly static Field OwnProjId = new Field("OwnProjId", "NPS_PUR_EPCEquipInOutCount", "所属项目Id");
			/// <summary>
			/// 管理层级名称
			/// </summary>
			public readonly static Field OwnProjName = new Field("OwnProjName", "NPS_PUR_EPCEquipInOutCount", "管理层级名称");
			/// <summary>
			/// EPS编号
			/// </summary>
			public readonly static Field EpsProjCode = new Field("EpsProjCode", "NPS_PUR_EPCEquipInOutCount", "EPS编号");
			/// <summary>
			/// EPS名称
			/// </summary>
			public readonly static Field EpsProjName = new Field("EpsProjName", "NPS_PUR_EPCEquipInOutCount", "EPS名称");
			/// <summary>
			/// 单位ID
			/// </summary>
			public readonly static Field CompanyID = new Field("CompanyID", "NPS_PUR_EPCEquipInOutCount", "单位ID");
			/// <summary>
			/// 单位编号
			/// </summary>
			public readonly static Field CompanyCode = new Field("CompanyCode", "NPS_PUR_EPCEquipInOutCount", "单位编号");
			/// <summary>
			/// 单位名称
			/// </summary>
			public readonly static Field CompanyName = new Field("CompanyName", "NPS_PUR_EPCEquipInOutCount", "单位名称");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ProfName = new Field("ProfName", "NPS_PUR_EPCEquipInOutCount", "");
		}
		#endregion
	}
}